const words = [
    {"no": "1", "word": "deep", "part": "adjective", "definition": "extending downward to a considerable degree"},
    {"no": "2", "word": "happy", "part": "adjective", "definition": "having the feeling arising from the consciousness of well-being"},
    {"no": "3", "word": "bump", "part": "verb", "definition": "to hit or knock typically with a degree of force or violence and making a thudding impact and usually with a degree of injury or damage"},
    {"no": "4", "word": "bear", "part": "noun", "definition": "an animal having long shaggy hair, feeding on fruit and insects as well as on flesh, and moving very fast for short distances"},
    {"no": "5", "word": "count", "part": "verb", "definition": "to separate one by one to find the total number of units : to number or tally"},
    {"no": "6", "word": "dunk", "part": "verb", "definition": "to dip (as a piece of bread, cake, or doughnut) into liquid (as coffee, milk, or tea) while eating"},
    {"no": "7", "word": "feet", "part": "plural noun", "definition": "the terminal parts of the vertebrate legs upon which an individual stands"},
    {"no": "8", "word": "cold", "part": "adjective", "definition": "having a temperature notably below that compatible with human comfort"},
    {"no": "9", "word": "alone", "part": "adjective", "definition": "away from other people or things"},
    {"no": "10", "word": "click", "part": "verb", "definition": "to select (something on a computer) by placing the cursor over it and pressing a button on your mouse"},
    {"no": "11", "word": "miss", "part": "verb", "definition": "to feel the lack of : to be unhappy because of the loss or absence of"},
    {"no": "12", "word": "shirt", "part": "noun", "definition": "a loose cloth garment usually having a collar, sleeves, a front opening, and a tail long enough to be tucked inside the waistband of trousers or a skirt"},
    {"no": "13", "word": "roof", "part": "noun", "definition": "the outside cover on top of a building or home"},
    {"no": "14", "word": "here", "part": "adverb", "definition": "at this point in space : in this location"},
    {"no": "15", "word": "lamp", "part": "noun", "definition": "a light-giving device"},
    {"no": "16", "word": "lost", "part": "adjective", "definition": "gone out of one's possession or control : put in an unremembered place"},
    {"no": "17", "word": "lunch", "part": "noun", "definition": "the meal that is eaten in the middle of the day"},
    {"no": "18", "word": "drift", "part": "verb", "definition": "to become driven or carried along by a current of water, wind, or air"},
    {"no": "19", "word": "please", "part": "adverb", "definition": "-used as a function word to express politeness or emphasis in a request"},
    {"no": "20", "word": "spill", "part": "verb", "definition": "to cause or allow to pour, splash, or fall out (as over the edge of a container) and be wasted, lost, or scattered"},
    {"no": "21", "word": "tired", "part": "adjective", "definition": "drained of strength and energy : fatigued often to the point of exhaustion : weary"},
    {"no": "22", "word": "large", "part": "adjective", "definition": "big"},
    {"no": "23", "word": "lake", "part": "noun", "definition": "a large body of water surrounded by land"},
    {"no": "24", "word": "grab", "part": "verb", "definition": "to take or take hold of by a sudden motion or grasp : to seize, to clutch"},
    {"no": "25", "word": "juice", "part": "noun", "definition": "the extractable fluid contents of plant cells or plant structures"},
    {"no": "26", "word": "nook", "part": "noun", "definition": "a secluded or out-of-the-way place or part"},
    {"no": "27", "word": "shops", "part": "verb", "definition": "examines goods and services with intent to buy"},
    {"no": "28", "word": "spot", "part": "noun", "definition": "a small extent of space"},
    {"no": "29", "word": "world", "part": "noun", "definition": "the earth with all its inhabitants and all things upon it"},
    {"no": "30", "word": "math", "part": "noun", "definition": "a science that deals with the relationship and symbolism of numbers"},
    {"no": "31", "word": "pick", "part": "verb", "definition": "to select from among a group"},
    {"no": "32", "word": "soap", "part": "noun", "definition": "a cleansing agent that is used for washing something"},
    {"no": "33", "word": "tools", "part": "plural noun", "definition": "instruments (such as hammers or saws) used or worked by hand"},
    {"no": "34", "word": "green", "part": "adjective", "definition": "being the color of grass or emeralds"},
    {"no": "35", "word": "muddy", "part": "adjective", "definition": "covered with a slimy sticky mixture of finely divided particles of solid material and water"},
    {"no": "36", "word": "ripe", "part": "adjective", "definition": "fully developed and so usable as food - used of fruit"},
    {"no": "37", "word": "sign", "part": "noun", "definition": "a board on a building that tells the name and type of a business"},
    {"no": "38", "word": "soup", "part": "noun", "definition": "a liquid food made with broth that often contains pieces of meat, fish, pasta, or vegetables"},
    {"no": "39", "word": "warm", "part": "adjective", "definition": "sending or giving out heat usually to a comfortable or beneficial degree : producing sensations of heat"},
    {"no": "40", "word": "fresh", "part": "adjective", "definition": "newly produced, gathered, or made"},
    {"no": "41", "word": "learn", "part": "verb", "definition": "to gain knowledge or understanding of or skill in by study, instruction, or experience"},
    {"no": "42", "word": "frosty", "part": "adjective", "definition": "cold, freezing"},
    {"no": "43", "word": "crisp", "part": "adjective", "definition": "easily broken, cracked, or snapped"},
    {"no": "44", "word": "shape", "part": "noun", "definition": "the visible makeup characteristic of a particular item or kind of item : characteristic appearance or visible form"},
    {"no": "45", "word": "splash", "part": "verb", "definition": "to strike and dash about (as water or mud) : to cause (a liquid or thinly viscous substance) to spatter or toss about especially with force"},
    {"no": "46", "word": "mushy", "part": "adjective", "definition": "soft, spongy"},
    {"no": "47", "word": "group", "part": "noun", "definition": "a relatively small number of individuals assembled or standing together"},
    {"no": "48", "word": "spine", "part": "noun", "definition": "the backbone of a book"},
    {"no": "49", "word": "straps", "part": "verb", "definition": "secures with or attaches by means of a narrow usually flat strip or thong of a flexible material"},
    {"no": "50", "word": "feast", "part": "noun", "definition": "an elaborate meal : a banquet"},
    {"no": "51", "word": "eagle", "part": "noun", "definition": "any of various large diurnal birds of prey noted for their strength, size, graceful figure, keenness of vision, and powers of flight"},
    {"no": "52", "word": "berries", "part": "plural noun", "definition": "pulpy and usually edible fruits of small size"},
    {"no": "53", "word": "caves", "part": "plural noun", "definition": "hollowed-out chambers in the earth or in the sides of cliffs or hills"},
    {"no": "54", "word": "blanket", "part": "noun", "definition": "a piece of warm fabric used as a bed covering"},
    {"no": "55", "word": "catch", "part": "verb", "definition": "to take hold of especially suddenly or forcibly : to grasp"},
    {"no": "56", "word": "updo", "part": "noun", "definition": "an upswept hairdo"},
    {"no": "57", "word": "mule", "part": "noun", "definition": "a hybrid between the horse and the donkey"},
    {"no": "58", "word": "glow", "part": "verb", "definition": "to shine with light or become lit up"},
    {"no": "59", "word": "quick", "part": "adjective", "definition": "done or taking place with rapidity : done or taking place within only a small interval of time"},
    {"no": "60", "word": "cotton", "part": "noun", "definition": "a soft fibrous usually white substance that clothes the seeds of various plants and is used extensively in the making of threads, yarns, and fabrics"},
    {"no": "61", "word": "seats", "part": "plural noun", "definition": "assigned or regularly assumed sitting places"},
    {"no": "62", "word": "baseball", "part": "noun", "definition": "a game played by two teams of nine in which players try to score runs by hitting a small ball with a bat and running to each of four bases located on a large field"},
    {"no": "63", "word": "great", "part": "adjective", "definition": "wonderful, admirable"},
    {"no": "64", "word": "playground", "part": "noun", "definition": "a piece of land used for and usually having special facilities for recreation especially by children"},
    {"no": "65", "word": "monster", "part": "noun", "definition": "a ferocious legendary animal usually of great size"},
    {"no": "66", "word": "enjoy", "part": "verb", "definition": "to make happy"},
    {"no": "67", "word": "jazzy", "part": "adjective", "definition": "of an unrestrained, animated, or flashy character"},
    {"no": "68", "word": "jeans", "part": "plural noun", "definition": "pants usually made of a durable twilled cotton cloth or denim and worn for work or sports"},
    {"no": "69", "word": "partner", "part": "noun", "definition": "one that is associated in any action with another : associate, colleague"},
    {"no": "70", "word": "raindrop", "part": "noun", "definition": "a liquid globule of water falling especially from the clouds"},
    {"no": "71", "word": "office", "part": "noun", "definition": "a place where a particular kind of business is transacted or a service is supplied"},
    {"no": "72", "word": "young", "part": "adjective", "definition": "in an early stage of life, growth, or development"},
    {"no": "73", "word": "outside", "part": "adverb", "definition": "in the open air"},
    {"no": "74", "word": "poem", "part": "noun", "definition": "writing in verse"},
    {"no": "75", "word": "pillow", "part": "noun", "definition": "a sack made typically of cloth and filled with a soft material used to support the head of a person resting or sleeping"},
    {"no": "76", "word": "steady", "part": "adjective", "definition": "firm in standing or position : not tottering or shaking : fixed"},
    {"no": "77", "word": "saturday", "part": "noun", "definition": "the seventh day of the week : the day following Friday"},
    {"no": "78", "word": "needle", "part": "noun", "definition": "a small slender rodlike instrument for hand sewing that has a round or elongated eye for thread at one end and a blunt or sharp point at the other and that is made usually of steel or bone in straight or curved form"},
    {"no": "79", "word": "above", "part": "adverb", "definition": "in a higher place : overhead"},
    {"no": "80", "word": "honking", "part": "verb", "definition": "causing (as a horn) to make a noise resembling the cry of a goose"},
    {"no": "81", "word": "strange", "part": "adjective", "definition": "unusual"},
    {"no": "82", "word": "noisy", "part": "adjective", "definition": "full of or characterized by the presence of sound"},
    {"no": "83", "word": "video", "part": "noun", "definition": "a recording of visual images and sound stored in digital form"},
    {"no": "84", "word": "timer", "part": "noun", "definition": "a stopwatch for timing races or contests"},
    {"no": "85", "word": "topics", "part": "plural noun", "definition": "subjects under discussion or consideration"},
    {"no": "86", "word": "layer", "part": "noun", "definition": "one thickness, course, or fold laid or lying over or under another"},
    {"no": "87", "word": "token", "part": "noun", "definition": "a piece or disk (as of metal) certified as having a definite value for payment or exchange"},
    {"no": "88", "word": "control", "part": "verb", "definition": "to have power over : to rule"},
    {"no": "89", "word": "summer", "part": "noun", "definition": "the season that consists of June, July, and August"},
    {"no": "90", "word": "across", "part": "preposition", "definition": "from one side to the opposite side of"},
    {"no": "91", "word": "stiff", "part": "adjective", "definition": "incapable of or resistant to being flexed or bent : rigid"},
    {"no": "92", "word": "running", "part": "verb", "definition": "going steadily by springing steps so that both feet leave the ground for an instant in each step"},
    {"no": "93", "word": "field", "part": "noun", "definition": "a land area free of woodland, cities, and towns : open country"},
    {"no": "94", "word": "behind", "part": "preposition", "definition": "toward the back : backward"},
    {"no": "95", "word": "trace", "part": "verb", "definition": "to copy (as a drawing, engraving, or manuscript) by following the lines or letters as seen through a transparent sheet superimposed on the original"},
    {"no": "96", "word": "below", "part": "preposition", "definition": "downward from"},
    {"no": "97", "word": "loose", "part": "adjective", "definition": "not rigidly fastened or securely attached : lacking a firm or tight connection : ready to move or come apart from an attachment"},
    {"no": "98", "word": "spare", "part": "adjective", "definition": "not being used : held for future or emergency use"},
    {"no": "99", "word": "cling", "part": "verb", "definition": "to adhere closely and firmly as if glued"},
    {"no": "100", "word": "grins", "part": "verb", "definition": "draws back the lips from the teeth in merriment or good humor"},
    {"no": "101", "word": "giraffe", "part": "noun", "definition": "a large fleet African ruminant mammal that is the tallest of living quadrupeds and has a very long rather stiff neck and a short coat of fawn or cream-colored hair marked with large reddish or brown blotches"},
    {"no": "102", "word": "groceries", "part": "plural noun", "definition": "articles of goods sold by a dealer in staple foodstuffs and usually meats and other foods"},
    {"no": "103", "word": "huddling", "part": "verb", "definition": "gathering in a group : pressing close together"},
    {"no": "104", "word": "jigsaw", "part": "noun", "definition": "a puzzle made by sawing or cutting a picture into small pieces to be fitted together"},
    {"no": "105", "word": "neighbors", "part": "plural noun", "definition": "ones that live next to or near others"},
    {"no": "106", "word": "gasped", "part": "verb", "definition": "caught the breath audibly often as an expression of shock, concern, or emotion"},
    {"no": "107", "word": "mansion", "part": "noun", "definition": "a home that is impressive due to its size"},
    {"no": "108", "word": "midday", "part": "noun", "definition": "noon"},
    {"no": "109", "word": "powwow", "part": "noun", "definition": "a North American Indian ceremony (as for the cure of disease, success in hunting, victory in war) often accompanied by great noise, feasting, and dancing"},
    {"no": "110", "word": "bazaar", "part": "noun", "definition": "a market place or market (as in the Middle East) that usually consists of rows of shops or stalls where all kinds of goods are offered for sale"},
    {"no": "111", "word": "astray", "part": "adverb", "definition": "into a wrong or mistaken way of thinking or acting"},
    {"no": "112", "word": "liquid", "part": "noun", "definition": "an extremely fluid substance that flows freely like water"},
    {"no": "113", "word": "fuel", "part": "noun", "definition": "a material (as coal, gas, oil, or wood) used to produce heat or power by burning"},
    {"no": "114", "word": "massive", "part": "adjective", "definition": "weighty : heavy"},
    {"no": "115", "word": "women", "part": "plural noun", "definition": "female human beings"},
    {"no": "116", "word": "chuckle", "part": "verb", "definition": "to laugh inwardly or quietly"},
    {"no": "117", "word": "handstand", "part": "noun", "definition": "an act of supporting the body on the hands with the trunk and legs balanced in air"},
    {"no": "118", "word": "machine", "part": "noun", "definition": "an assemblage of parts that are usually solid bodies that transmit forces, motion, and energy one to another in some predetermined manner and to some desired end (as for sewing a seam, hoisting a load, or maintaining an electric current)"},
    {"no": "119", "word": "leaking", "part": "verb", "definition": "letting a substance (as water or gas) or light in or out through a hole, crevice, or other opening"},
    {"no": "120", "word": "snazzy", "part": "adjective", "definition": "outstanding in style : conspicuously or flashily attractive"},
    {"no": "121", "word": "whee", "part": "interjection", "definition": "—used to express delight or general exuberance"},
    {"no": "122", "word": "welcome", "part": "noun", "definition": "a friendly greeting or reception given to a person when he or she arrives"},
    {"no": "123", "word": "pretend", "part": "verb", "definition": "to make believe"},
    {"no": "124", "word": "should", "part": "verb", "definition": "—used in auxiliary function to express what is probable or expected"},
    {"no": "125", "word": "sideways", "part": "adverb", "definition": "in a position so as to offer only the right or left lateral part of the body"},
    {"no": "126", "word": "muster", "part": "verb", "definition": "to bring together : to collect"},
    {"no": "127", "word": "include", "part": "verb", "definition": "to place, list, or rate as a part or component of a whole or of a larger group, class, or aggregate"},
    {"no": "128", "word": "sandwich", "part": "noun", "definition": "two pieces of bread with meat or cheese or a mixture of foods placed between them"},
    {"no": "129", "word": "saturn", "part": "noun", "definition": "the planet sixth in order from the sun that is notable for its large ring system"},
    {"no": "130", "word": "violet", "part": "noun", "definition": "a small-flowered plant of a genus of usually spring-blooming flowers that have leafy stems and purple, yellow, or white flowers"},
    {"no": "131", "word": "mighty", "part": "adjective", "definition": "having or wielding great power or authority"},
    {"no": "132", "word": "solution", "part": "noun", "definition": "an answer to or a means of answering a problem : an explanation"},
    {"no": "133", "word": "spiral", "part": "adjective", "definition": "winding around a center point and slowly moving away from or getting closer to it"},
    {"no": "134", "word": "thread", "part": "noun", "definition": "a filament, a group of filaments twisted together, or a filamentous length formed by spinning and twisting short textile fibers into a continuous strand"},
    {"no": "135", "word": "velvet", "part": "noun", "definition": "a clothing and upholstery fabric in a wide range of constructions and weights made of silk, rayon, cotton, nylon, or wool and characterized by a short soft dense pile"},
    {"no": "136", "word": "breathe", "part": "verb", "definition": "to draw air into and expel it out of the lungs : to inhale and exhale"},
    {"no": "137", "word": "taxicab", "part": "noun", "definition": "a chauffeur-driven automobile available on call to carry a passenger between any two points (as within a city) for a fare"},
    {"no": "138", "word": "report", "part": "noun", "definition": "a usually detailed account or statement"},
    {"no": "139", "word": "cobweb", "part": "noun", "definition": "a single thread spun by a spider"},
    {"no": "140", "word": "rodent", "part": "noun", "definition": "an animal of an order comprising relatively small gnawing mammals"},
    {"no": "141", "word": "spying", "part": "verb", "definition": "watching (as a person) in a furtive or stealthy manner for the purpose of secretly obtaining information for usually hostile purposes"},
    {"no": "142", "word": "showed", "part": "verb", "definition": "gave an explanation of : taught, informed, instructed"},
    {"no": "143", "word": "scribbly", "part": "adjective", "definition": "covered with or consisting of illegible or random marks written or drawn"},
    {"no": "144", "word": "recess", "part": "noun", "definition": "a time between classes during the school day that is used for rest or play"},
    {"no": "145", "word": "highway", "part": "noun", "definition": "a main direct road"},
    {"no": "146", "word": "reeds", "part": "plural noun", "definition": "tall grasses with slender often prominently jointed stems that grow especially in wet areas"},
    {"no": "147", "word": "bolts", "part": "plural noun", "definition": "wood or metal bars or rods used to fasten a door"},
    {"no": "148", "word": "squeeze", "part": "verb", "definition": "to exert pressure especially on opposite sides or parts of : to press together closely or tightly"},
    {"no": "149", "word": "softly", "part": "adverb", "definition": "in a manner that is pleasing or agreeable to the senses"},
    {"no": "150", "word": "wriggle", "part": "verb", "definition": "to move the body or a bodily part to and fro with short writhing motions like a worm : to squirm, writhe"},
    {"no": "151", "word": "motion", "part": "noun", "definition": "the action or process of a body passing from one place or position to another"},
    {"no": "152", "word": "terror", "part": "noun", "definition": "a state of intense fright or apprehension : stark fear"},
    {"no": "153", "word": "murky", "part": "adjective", "definition": "dark or dull in color"},
    {"no": "154", "word": "harvest", "part": "noun", "definition": "the amount of any natural product that is gathered"},
    {"no": "155", "word": "quill", "part": "noun", "definition": "a bird’s feather; especially : one of the large stiff feathers of a bird’s wing or tail"},
    {"no": "156", "word": "patio", "part": "noun", "definition": "a usually paved outdoor area that is next to a building and is used for dining and relaxing"},
    {"no": "157", "word": "braids", "part": "plural noun", "definition": "lengths of hair done up by interweaving three or more strands together"},
    {"no": "158", "word": "castle", "part": "noun", "definition": "a large fortified building often surrounded by a moat"},
    {"no": "159", "word": "costume", "part": "noun", "definition": "an outfit worn to create the appearance characteristic of a particular period, person, place, or thing"},
    {"no": "160", "word": "wagon", "part": "noun", "definition": "a heavy four-wheel usually uncovered vehicle designed especially for transporting bulky commodities and drawn originally by animals"},
    {"no": "161", "word": "wrench", "part": "verb", "definition": "twist violently to one side or out of line, shape, or position"},
    {"no": "162", "word": "indeed", "part": "adverb", "definition": "admittedly, undeniably"},
    {"no": "163", "word": "gerbils", "part": "plural noun", "definition": "burrowing desert rodents that have long hind legs well adapted for leaping"},
    {"no": "164", "word": "village", "part": "noun", "definition": "a small cluster of houses and other buildings (as stores and churches) forming a unit distinct from the surrounding countryside"},
    {"no": "165", "word": "critters", "part": "plural noun", "definition": "creatures, animals"},
    {"no": "166", "word": "stifle", "part": "verb", "definition": "to withhold from expression : to keep in check : to repress"},
    {"no": "167", "word": "dimple", "part": "noun", "definition": "a slight natural indentation or hollow in the surface of some part of the human body (as on a cheek or the chin)"},
    {"no": "168", "word": "brother", "part": "noun", "definition": "a male human being considered in his relation to another person having the same parents or having one parent in common"},
    {"no": "169", "word": "mistake", "part": "noun", "definition": "an unintentional error"},
    {"no": "170", "word": "harbor", "part": "noun", "definition": "a small bay or other sheltered part of a considerable body of water usually well protected against high waves and strong currents and deep enough to anchor ships or other craft"},
    {"no": "171", "word": "reunion", "part": "noun", "definition": "a meeting of persons long separated"},
    {"no": "172", "word": "balloon", "part": "noun", "definition": "a bag of silk or other tough light material shaped usually like a sphere, made nonporous, and filled with heated air or a gas lighter than air"},
    {"no": "173", "word": "promise", "part": "noun", "definition": "a statement that you will do or not do something specific"},
    {"no": "174", "word": "uproar", "part": "noun", "definition": "a loud usually disorderly noise of some duration"},
    {"no": "175", "word": "wednesday", "part": "noun", "definition": "the day following Tuesday"},
    {"no": "176", "word": "exactly", "part": "adverb", "definition": "precisely according to a rule, standard, or fact : accurately"},
    {"no": "177", "word": "severe", "part": "adjective", "definition": "strict or uncompromising in judgment, discipline, or government"},
    {"no": "178", "word": "twinkle", "part": "verb", "definition": "to shine with a flickering, sparkling, or intermittent light"},
    {"no": "179", "word": "snicker", "part": "verb", "definition": "to laugh in a slight, covert, or partly suppressed manner (as in derision or from embarrassment)"},
    {"no": "180", "word": "stumble", "part": "verb", "definition": "to lose one’s footing in walking or running so as to stagger or fall : to trip"},
    {"no": "181", "word": "smock", "part": "noun", "definition": "a lightweight loose garment with a front opening and worn especially for protection of clothing while working"},
    {"no": "182", "word": "natural", "part": "adjective", "definition": "in accordance with or determined by nature : based upon the operations of the physical world"},
    {"no": "183", "word": "childhood", "part": "noun", "definition": "the quality or state of being a young person especially between infancy and youth"},
    {"no": "184", "word": "nonsense", "part": "noun", "definition": "something that is not capable of being understood"},
    {"no": "185", "word": "bandits", "part": "plural noun", "definition": "those who steal, especially in a shameless or pitiless manner"},
    {"no": "186", "word": "champion", "part": "noun", "definition": "someone whose superiority is formally acknowledged especially after a test, contest, or series of tests or contests"},
    {"no": "187", "word": "superb", "part": "adjective", "definition": "of the highest quality"},
    {"no": "188", "word": "tinge", "part": "verb", "definition": "to color with a slight shade or stain : to tint"},
    {"no": "189", "word": "outcome", "part": "noun", "definition": "something that follows from an activity or process : consequence, result"},
    {"no": "190", "word": "groves", "part": "plural noun", "definition": "smaller groups of trees than forests often without underwood and planted or growing naturally as if arranged by art"},
    {"no": "191", "word": "ghostly", "part": "adjective", "definition": "of or relating to a mark or visible sign left by something dead, lost, or no longer present"},
    {"no": "192", "word": "convince", "part": "verb", "definition": "to get someone to agree or believe by arguing a point"},
    {"no": "193", "word": "biology", "part": "noun", "definition": "the science of life"},
    {"no": "194", "word": "captive", "part": "adjective", "definition": "kept within bounds : confined"},
    {"no": "195", "word": "streamers", "part": "plural noun", "definition": "narrow free-floating strips (as of cloth or crepe paper)"},
    {"no": "196", "word": "speckled", "part": "adjective", "definition": "covered or marked with small marks or splotches : spotted"},
    {"no": "197", "word": "hopscotch", "part": "noun", "definition": "a child’s game in which a player tosses a small object into the lined and numbered areas outlined on the ground, hops on one foot through the figure and back to the area in which the object lies, picks it up, and hops out trying to avoid errors"},
    {"no": "198", "word": "jumbled", "part": "adjective", "definition": "lacking order, coherence, sequence, or plan"},
    {"no": "199", "word": "naughty", "part": "adjective", "definition": "violating accepted standards of morality, good taste, or polite behavior"},
    {"no": "200", "word": "dodgy", "part": "adjective", "definition": "evasive, tricky"},
    {"no": "201", "word": "ballerina", "part": "noun", "definition": "a female dancer in a form of artistic dancing"},
    {"no": "202", "word": "cubism", "part": "noun", "definition": "the arbitrary arrangement and interrelation of contours and fragments of contours on a picture surface without necessary reference to natural objects or their structure"},
    {"no": "203", "word": "interact", "part": "verb", "definition": "to have an effect on one another"},
    {"no": "204", "word": "jerky", "part": "noun", "definition": "meat (as beef) that has been cut into long slices or strips and dried"},
    {"no": "205", "word": "diablo", "part": "noun", "definition": "an extremely and malignantly wicked person : a human fiend"},
    {"no": "206", "word": "ablaze", "part": "adjective", "definition": "on fire"},
    {"no": "207", "word": "pivot", "part": "noun", "definition": "a dance step in which the dancer rotates on one foot and completes the step by shifting the weight to the other foot"},
    {"no": "208", "word": "karate", "part": "noun", "definition": "a Japanese art of self-defense in which kicks and openhanded blows are delivered especially to vulnerable parts of the body"},
    {"no": "209", "word": "bowler", "part": "noun", "definition": "a stiff felt hat with a dome-shaped crown and a rather narrow somewhat rolled brim — called also “Derby”"},
    {"no": "210", "word": "phantom", "part": "adjective", "definition": "unembodied, elusive"},
    {"no": "211", "word": "locust", "part": "noun", "definition": "a grasshopper that frequently travels in swarms"},
    {"no": "212", "word": "council", "part": "noun", "definition": "a somewhat permanent group elected or appointed to constitute an advisory body or a body with a degree of legislative power"},
    {"no": "213", "word": "ointment", "part": "noun", "definition": "a salve or unguent for application to the skin; specifically : a semisolid medicinal preparation usually having a base of fatty or greasy material"},
    {"no": "214", "word": "gothic", "part": "adjective", "definition": "of, relating to or having the characteristics of a European style of architecture from the 12th to the 16th centuries that is characterized by slender vertical piers and counterbalancing buttresses, and with pointed arches and vaulting"},
    {"no": "215", "word": "midair", "part": "noun", "definition": "any point or region in the air not immediately adjacent to the ground or other solid or liquid surface beneath it"},
    {"no": "216", "word": "hurricane", "part": "noun", "definition": "a tropical cyclone with winds of 73 miles per hour or greater"},
    {"no": "217", "word": "laurel", "part": "noun", "definition": "a recognition of superior achievement : a mark of public esteem : an honor"},
    {"no": "218", "word": "lollygag", "part": "verb", "definition": "to fool around : to loiter, dawdle"},
    {"no": "219", "word": "vermin", "part": "plural noun", "definition": "small common harmful animals (such as bedbugs and mice) that tend to occur in great numbers and are difficult to control"},
    {"no": "220", "word": "argument", "part": "noun", "definition": "the act or process of contending or disagreeing in words : a disputation"},
    {"no": "221", "word": "wreckage", "part": "noun", "definition": "the remains of the destruction, disorganization, or serious injury of something especially by violence"},
    {"no": "222", "word": "dolphin", "part": "noun", "definition": "any of various small marine toothed whales that have the snout more or less elongated into a beak and the neck vertebrae partially fused"},
    {"no": "223", "word": "infinite", "part": "adjective", "definition": "having no end : extending indefinitely"},
    {"no": "224", "word": "bittersweet", "part": "adjective", "definition": "of or relating to a prepared chocolate containing little sugar"},
    {"no": "225", "word": "fend", "part": "verb", "definition": "to look out for oneself : to manage"},
    {"no": "226", "word": "disguise", "part": "noun", "definition": "unfamiliar or uncharacteristic style of dress worn to conceal one’s identity"},
    {"no": "227", "word": "membrane", "part": "noun", "definition": "a thin soft pliable sheet or layer especially of animal or vegetable origin"},
    {"no": "228", "word": "magnolia", "part": "noun", "definition": "a tree or shrub that has evergreen or deciduous leaves and usually showy white, yellow, rose, or purple flowers appearing in early spring"},
    {"no": "229", "word": "sensation", "part": "noun", "definition": "a state of excited interest or feeling"},
    {"no": "230", "word": "daredevil", "part": "noun", "definition": "a person who without apparent fear faces, accepts, or carries out anything unusually dangerous or foolhardy"},
    {"no": "231", "word": "bypass", "part": "noun", "definition": "a passage providing an alternative deflected route (such as a road to carry traffic around a congested district or a channel to deflect flood water)"},
    {"no": "232", "word": "oysters", "part": "plural noun", "definition": "marine bivalve mollusks having a rough irregular shell, living free on the bottom or adhering to stones or other objects in shallow water, and feeding on minute plants and animals carried to them by the current"},
    {"no": "233", "word": "military", "part": "adjective", "definition": "of or relating to soldiers, arms, or war"},
    {"no": "234", "word": "gasket", "part": "noun", "definition": "a separate or attached sealer used in making and closing airtight or liquid containers to ensure tightness"},
    {"no": "235", "word": "biceps", "part": "noun", "definition": "a muscle having two heads, such as the large flexor muscle of the front of the upper arm"},
    {"no": "236", "word": "voyage", "part": "noun", "definition": "a journey by water : cruise"},
    {"no": "237", "word": "advantage", "part": "noun", "definition": "a more favorable or improved position or condition"},
    {"no": "238", "word": "applause", "part": "noun", "definition": "approval publicly expressed (as by clapping hands)"},
    {"no": "239", "word": "nostrils", "part": "plural noun", "definition": "the external openings of the nose or nasal cavity of a vertebrate"},
    {"no": "240", "word": "television", "part": "noun", "definition": "a medium of communication whereby images and sounds are transmitted"},
    {"no": "241", "word": "mattress", "part": "noun", "definition": "a resilient pad for use as a resting place alone or supported on a bedstead"},
    {"no": "242", "word": "soldier", "part": "noun", "definition": "a person engaged in military service"},
    {"no": "243", "word": "trousers", "part": "plural noun", "definition": "an outer garment extending from the waist to the ankle or sometimes only to or just below the knee"},
    {"no": "244", "word": "albums", "part": "plural noun", "definition": "one or more recordings produced as a single unit"},
    {"no": "245", "word": "muscles", "part": "plural noun", "definition": "tissues that function to produce motion and are made up of variously modified elongated cells capable of contracting when stimulated"},
    {"no": "246", "word": "diploma", "part": "noun", "definition": "a document that records that a person has completed a course or graduated from a school"},
    {"no": "247", "word": "harpoons", "part": "plural noun", "definition": "throwing weapons used in hunting large fish and sea animals"},
    {"no": "248", "word": "rampage", "part": "noun", "definition": "a state of being turbulently active, wildly agitated, or destructive"},
    {"no": "249", "word": "levitate", "part": "verb", "definition": "to rise or float in the air, especially in seeming defiance of gravitation"},
    {"no": "250", "word": "spritzed", "part": "verb", "definition": "sprayed, squirted"},
    {"no": "251", "word": "clientele", "part": "noun", "definition": "a body of patrons or customers"},
    {"no": "252", "word": "anecdotes", "part": "plural noun", "definition": "usually short narratives of interesting, amusing, or curious incidents often biographical and generally characterized by human interest"},
    {"no": "253", "word": "haberdasher", "part": "noun", "definition": "a dealer in men’s furnishings, such as shirts, ties, and hats"},
    {"no": "254", "word": "filigree", "part": "noun", "definition": "ornamental work of fine wire of gold, silver, or copper that is used chiefly to decorate gold and silver surfaces"},
    {"no": "255", "word": "catapults", "part": "plural noun", "definition": "ancient military devices used for hurling heavy missiles (as stones) or for hurling other missiles (as spears, arrows) with extreme force"},
    {"no": "256", "word": "embroiled", "part": "verb", "definition": "involved especially in conflict or with a problem, adversaries, or the law"},
    {"no": "257", "word": "burro", "part": "noun", "definition": "a donkey"},
    {"no": "258", "word": "guava", "part": "noun", "definition": "the globular yellow fruit of a small shrubby tropical American tree"},
    {"no": "259", "word": "crescendo", "part": "noun", "definition": "the peak of a gradual increase (as in physical or emotional force or intensity)"},
    {"no": "260", "word": "ocelot", "part": "noun", "definition": "a medium-sized American wildcat ranging from Texas to Patagonia and having a tawny yellow or grayish coat that is dotted and striped with black"},
    {"no": "261", "word": "onyx", "part": "adjective", "definition": "of the color jet black"},
    {"no": "262", "word": "demigod", "part": "noun", "definition": "a mythological divine or semidivine being (as the offspring of a deity and a mortal)"},
    {"no": "263", "word": "trek", "part": "noun", "definition": "a trip or movement especially when involving difficulties or complex organization"},
    {"no": "264", "word": "teriyaki", "part": "noun", "definition": "a dish of Japanese origin consisting of meat or fish that is grilled or broiled after being marinated in a seasoned soy sauce"},
    {"no": "265", "word": "contribute", "part": "verb", "definition": "to add (as knowledge or effort) to a common interest or activity"},
    {"no": "266", "word": "hocus-pocus", "part": "noun", "definition": "something that confuses, misleads, or is difficult to comprehend"},
    {"no": "267", "word": "narwhal", "part": "noun", "definition": "an arctic cetacean that has no dorsal fin, is marbled black and white in color, reaches a length of about 16 feet, and possesses in the male one or rarely two long, spirally twisted pointed tusks"},
    {"no": "268", "word": "melancholy", "part": "adjective", "definition": "depressed in spirits : mournful"},
    {"no": "269", "word": "merfolk", "part": "plural noun", "definition": "legendary peoples of the sea having human head, trunk, and arms and the tail of a fish"},
    {"no": "270", "word": "gargoyles", "part": "plural noun", "definition": "spouts often having the form of a grotesque figure or animal and projecting from a roof gutter to throw rainwater clear of a building"},
    {"no": "271", "word": "pavilions", "part": "plural noun", "definition": "light sometimes ornamental structures in gardens, parks, or places of recreation that are used for entertainment or shelter"},
    {"no": "272", "word": "skeptical", "part": "adjective", "definition": "characterized by an attitude of doubt or disposition in regard to something particular (such as a supposed fact)"},
    {"no": "273", "word": "palette", "part": "noun", "definition": "a particular range, quality, or use of color"},
    {"no": "274", "word": "ogres", "part": "plural noun", "definition": "hideous giants represented in fairy tales and folklore as feeding on human beings : monsters"},
    {"no": "275", "word": "goatee", "part": "noun", "definition": "a small trim pointed or tufted beard on a man’s chin"},
    {"no": "276", "word": "grotesque", "part": "adjective", "definition": "departing markedly from the natural, the expected or the typical (as by distortion, exaggeration) : atypical"},
    {"no": "277", "word": "threshold", "part": "noun", "definition": "the place or point of entering or beginning : outset"},
    {"no": "278", "word": "flamboyant", "part": "adjective", "definition": "marked by strikingly elaborate, colorful, or showy display or behavior"},
    {"no": "279", "word": "famine", "part": "noun", "definition": "a period of extreme scarcity of food"},
    {"no": "280", "word": "linoleum", "part": "noun", "definition": "a floor covering made by laying on a burlap or canvas backing a mixture of solidified linseed oil and various solid particles and usually pigments"},
    {"no": "281", "word": "pesos", "part": "plural noun", "definition": "coins or currency notes representing any of the basic monetary units of Argentina, Chile, Colombia, Cuba, Dominican Republic, Mexico, and Uruguay"},
    {"no": "282", "word": "rogue", "part": "noun", "definition": "a dishonest unprincipled person"},
    {"no": "283", "word": "amnesia", "part": "noun", "definition": "loss of memory sometimes including the memory of personal identity"},
    {"no": "284", "word": "fruition", "part": "noun", "definition": "completion, fulfillment"},
    {"no": "285", "word": "bygone", "part": "adjective", "definition": "of or relating to the past"},
    {"no": "286", "word": "committee", "part": "noun", "definition": "a group of people delegated to consider, investigate, or act on and usually to report on some matter or business"},
    {"no": "287", "word": "mirage", "part": "noun", "definition": "an optical phenomenon observed on still days over deserts or hot pavements that has the mirrorlike appearance of a quiet pool of water"},
    {"no": "288", "word": "newfangled", "part": "adjective", "definition": "recently made or of the most up-to-date style"},
    {"no": "289", "word": "surcharge", "part": "noun", "definition": "a price demanded for a thing or service in excess of the usual or normal amount"},
    {"no": "290", "word": "marksmanship", "part": "noun", "definition": "the art or skill of a person practiced at hitting a target especially with firearms"},
    {"no": "291", "word": "column", "part": "noun", "definition": "one of a building’s vertical supporting structures"},
    {"no": "292", "word": "plaque", "part": "noun", "definition": "an inscribed metal tablet that identifies a site or commemorates an individual or event"},
    {"no": "293", "word": "rebuke", "part": "verb", "definition": "to criticize sharply: to reprimand"},
    {"no": "294", "word": "adversity", "part": "noun", "definition": "a condition of suffering, destitution, or affliction often implying previous prosperity or well-being"},
    {"no": "295", "word": "symphony", "part": "noun", "definition": "a large piece for orchestra usually in three or four contrasting movements"},
    {"no": "296", "word": "aquamarine", "part": "noun", "definition": "a pale blue to light greenish blue"},
    {"no": "297", "word": "altar", "part": "noun", "definition": "a tablelike construction used in the Christian church in celebrating the Eucharist : communion table"},
    {"no": "298", "word": "stylistic", "part": "adjective", "definition": "of or relating to mode of expression especially in the use of language"},
    {"no": "299", "word": "flailed", "part": "verb", "definition": "moved, swung, or beat as though wielding an instrument for threshing grain from the ear by hand"},
    {"no": "300", "word": "errands", "part": "plural noun", "definition": "trips made in order to deliver a message or purchase or attend to something"},
    {"no": "301", "word": "spree", "part": "noun", "definition": "an unrestrained and usually excessive indulgence in or outburst of any activity : splurge, rampage"},
    {"no": "302", "word": "steeped", "part": "verb", "definition": "saturated thoroughly : imbued"},
    {"no": "303", "word": "smattering", "part": "noun", "definition": "an inconsiderable number or amount especially of similar but distinct individuals or parts : piecemeal collection"},
    {"no": "304", "word": "bibliophile", "part": "noun", "definition": "a lover of books especially for beautiful or rare qualities of format; also : a book collector"},
    {"no": "305", "word": "graphite", "part": "noun", "definition": "a mineral consisting of soft black lustrous carbon that conducts electricity and is used in pencils, crucibles, electrolytic anodes, as a lubricant, and as a moderator in atomic-energy plants—called also “black lead”"},
    {"no": "306", "word": "halo", "part": "noun", "definition": "the aura of glory, veneration, prestige, or sentiment surrounding an idealized person or thing"},
    {"no": "307", "word": "feisty", "part": "adjective", "definition": "having or showing a lively aggressiveness : spunky"},
    {"no": "308", "word": "transfixed", "part": "verb", "definition": "held motionless by or as if by piercing especially with an absorbing emotion or interest"},
    {"no": "309", "word": "aluminum", "part": "noun", "definition": "a bluish silver-white metallic element that is the most plentiful metal in Earth’s crust"},
    {"no": "310", "word": "residential", "part": "adjective", "definition": "used as a temporary or permanent dwelling place, abode, or habitation to which one intends to return"},
    {"no": "311", "word": "deposition", "part": "noun", "definition": "testimony taken down in writing under oath or affirmation"},
    {"no": "312", "word": "veterinarian", "part": "noun", "definition": "one qualified and duly authorized to treat diseases of animals"},
    {"no": "313", "word": "skiff", "part": "noun", "definition": "a light rowboat"},
    {"no": "314", "word": "totem", "part": "noun", "definition": "an animal, plant, or other object serving as the emblem of a family or clan and often regarded as a reminder of its ancestry"},
    {"no": "315", "word": "inferno", "part": "noun", "definition": "a large disastrous burning : a conflagration"},
    {"no": "316", "word": "buzzard", "part": "noun", "definition": "any of various birds of prey such as a turkey vulture or a condor"},
    {"no": "317", "word": "eliminate", "part": "verb", "definition": "to get rid of"},
    {"no": "318", "word": "writhes", "part": "verb", "definition": "becomes twisted, contorted, or wrested about in or as if in pain or struggling"},
    {"no": "319", "word": "mourners", "part": "plural noun", "definition": "those that are sorrowful over a death"},
    {"no": "320", "word": "respiratory", "part": "adjective", "definition": "of or relating to breathing"},
    {"no": "321", "word": "perpetrate", "part": "verb", "definition": "to be guilty of (a crime, an offense, etc.) : to commit"},
    {"no": "322", "word": "intestines", "part": "plural noun", "definition": "tubular portions of the digestive tract that in the vertebrate lie posterior to the stomach from which they are separated by the pyloric valve"},
    {"no": "323", "word": "sanitation", "part": "noun", "definition": "the application of measures to make environmental conditions favorable to health"},
    {"no": "324", "word": "barren", "part": "adjective", "definition": "deficient in producing vegetation : bare or desolate"},
    {"no": "325", "word": "lavishly", "part": "adverb", "definition": "in a manner characterized by profusion or excess"},
    {"no": "326", "word": "suffice", "part": "verb", "definition": "to be enough : to meet or satisfy a need"},
    {"no": "327", "word": "giddily", "part": "adverb", "definition": "in a manner characterized by exuberance, impulsiveness, or thoughtlessness"},
    {"no": "328", "word": "tiff", "part": "noun", "definition": "a slight fit of anger : an outburst of temper or spite : a petty quarrel"},
    {"no": "329", "word": "leeward", "part": "adjective", "definition": "situated away from the wind : downwind"},
    {"no": "330", "word": "hurly-burly", "part": "noun", "definition": "confusion, turmoil, uproar"},
    {"no": "331", "word": "monotone", "part": "noun", "definition": "a succession of syllables, words, or sentences in one unvaried key or pitch"},
    {"no": "332", "word": "parroting", "part": "verb", "definition": "imitating the form of without understanding the sense or meaning involved"},
    {"no": "333", "word": "techie", "part": "noun", "definition": "a person who is very knowledgeable or enthusiastic about the science of the application of knowledge to practical purposes"},
    {"no": "334", "word": "gruesome", "part": "adjective", "definition": "inspiring horror or repulsion : fearful, grisly, hideous"},
    {"no": "335", "word": "tsunami", "part": "noun", "definition": "a great sea wave produced by submarine earth movement or volcanic eruption : a tidal wave"},
    {"no": "336", "word": "anomaly", "part": "noun", "definition": "something deviating from a general rule, method, or analogy : something irregular or abnormal"},
    {"no": "337", "word": "banishment", "part": "noun", "definition": "legal expulsion from a country"},
    {"no": "338", "word": "magenta", "part": "noun", "definition": "a deep purplish red"},
    {"no": "339", "word": "conveyance", "part": "noun", "definition": "the action of transporting : transportation"},
    {"no": "340", "word": "cohort", "part": "noun", "definition": "company, band, group"},
    {"no": "341", "word": "kindling", "part": "noun", "definition": "easily combustible material of a convenient size for starting a fire"},
    {"no": "342", "word": "treachery", "part": "noun", "definition": "betrayal of trust"},
    {"no": "343", "word": "manana", "part": "adverb", "definition": "at an indefinite time in the future – used chiefly in the Southwest"},
    {"no": "344", "word": "squeal", "part": "verb", "definition": "to cry with a sharp shrill prolonged sound"},
    {"no": "345", "word": "tersely", "part": "adverb", "definition": "in a brief and concise manner"},
    {"no": "346", "word": "autism", "part": "noun", "definition": "a developmental disorder that typically appears by age three and that is variable in expression but is recognized and diagnosed by impairment of the ability to form social relationships, by impairment of the ability to communicate with others, and by stereotyped behavior patterns"},
    {"no": "347", "word": "foyer", "part": "noun", "definition": "an anteroom or lobby especially of a theater, library, or other public building"},
    {"no": "348", "word": "straightforward", "part": "adjective", "definition": "free from the use of an unnecessarily large number of words to express an idea : direct or not roundabout in expression"},
    {"no": "349", "word": "vial", "part": "noun", "definition": "a small vessel for liquids"},
    {"no": "350", "word": "foist", "part": "verb", "definition": "to force another to accept especially by stealth or deceit"},
    {"no": "351", "word": "samhain", "part": "noun", "definition": "the evening preceding All Saints’ Day : Halloween"},
    {"no": "352", "word": "crystalline", "part": "adjective", "definition": "transparent, pure, pellucid"},
    {"no": "353", "word": "sentient", "part": "adjective", "definition": "conscious or capable of fine distinctions or perceptions : sensitive"},
    {"no": "354", "word": "technicalities", "part": "plural noun", "definition": "details that have meaning only for the specialist"},
    {"no": "355", "word": "crannies", "part": "plural noun", "definition": "small obscure clefts, corners, or closed spaces that are easy to overlook and are likely places for concealing something or for hiding"},
    {"no": "356", "word": "incorporeal", "part": "adjective", "definition": "having no material body or form : not consisting of matter"},
    {"no": "357", "word": "tlingit", "part": "noun", "definition": "a group of Indian peoples of the islands and coast of southern Alaska"},
    {"no": "358", "word": "detainees", "part": "plural noun", "definition": "persons held in custody for political reasons"},
    {"no": "359", "word": "delinquent", "part": "noun", "definition": "a transgressor against duty or law especially in a degree not constituting crime"},
    {"no": "360", "word": "grudgingly", "part": "adverb", "definition": "in a manner that is unwilling, reluctant, illiberal, or ungenerous"},
    {"no": "361", "word": "smoldering", "part": "verb", "definition": "wasting away by slow combustion"},
    {"no": "362", "word": "karma", "part": "noun", "definition": "the sum total of the ethical consequences of a person’s good or bad actions comprising thoughts, words, and deeds that is held in Hinduism and Buddhism to determine one’s specific destiny in one’s next existence"},
    {"no": "363", "word": "cyclops", "part": "noun", "definition": "one of a race of giants in Greek mythology with a single eye in the middle of the forehead"},
    {"no": "364", "word": "translucent", "part": "adjective", "definition": "admitting and diffusing light so that objects beyond cannot be clearly distinguished : partly transparent"},
    {"no": "365", "word": "glabrous", "part": "adjective", "definition": "having a smooth even surface : free of roughness; specifically : having an epidermal covering that is totally or relatively devoid of hairs or down"},
    {"no": "366", "word": "gondolas", "part": "plural noun", "definition": "long narrow flat-bottomed boats with a high prow and stern used on the canals of Venice"},
    {"no": "367", "word": "pentameter", "part": "noun", "definition": "a line of five metrical feet"},
    {"no": "368", "word": "chlorofluorocarbon", "part": "noun", "definition": "any of several simple gaseous compounds used as refrigerants, cleaning solvents, and aerosol propellants and in the manufacture of plastic foams, and that are believed to be a major cause of stratospheric ozone depletion"},
    {"no": "369", "word": "impeccable", "part": "adjective", "definition": "free from fault or blame : flawless"},
    {"no": "370", "word": "inimitable", "part": "adjective", "definition": "not capable of being copied : matchless"},
    {"no": "371", "word": "euphoria", "part": "noun", "definition": "a feeling of well-being or elation"},
    {"no": "372", "word": "euphrates", "part": "geographical entry", "definition": "river 1,700 miles long in southwestern Asia flowing from eastern Turkey southeast through Syria and Iraq to unite with the Tigris forming the Shatt al Arab"},
    {"no": "373", "word": "artificial", "part": "adjective", "definition": "produced by human beings and intended to imitate something in nature : simulated"},
    {"no": "374", "word": "villainous", "part": "adjective", "definition": "highly objectionable : mean, bad, wretched, vile, detestable"},
    {"no": "375", "word": "ruffian", "part": "noun", "definition": "a coarse, brutal, or cruel fellow"},
    {"no": "376", "word": "buccaneer", "part": "noun", "definition": "one of the pirates preying upon Spanish ships and settlements especially in the West Indies in the seventeenth century"},
    {"no": "377", "word": "lubbers", "part": "plural noun", "definition": "clumsy or unskilled seamen"},
    {"no": "378", "word": "louis dor", "part": "noun", "definition": "a French gold coin first struck in 1640 and issued up to the Revolution"},
    {"no": "379", "word": "ambiguity", "part": "noun", "definition": "the condition of admitting of two or more meanings, of being understood in more than one way, or of referring to two or more things at the same time"},
    {"no": "380", "word": "cache", "part": "noun", "definition": "something that is hidden or stored in a secret or secure place"},
    {"no": "381", "word": "madagascar", "part": "geographical entry", "definition": "an island in the western Indian Ocean off southeastern Africa that is known for its unique flora and fauna"},
    {"no": "382", "word": "catechism", "part": "noun", "definition": "a manual or guide for systematic instruction (as for moral and religious instruction) sometimes in the form of a comprehensive summary of doctrine and often in the form of questions and answers"},
    {"no": "383", "word": "lieutenant", "part": "noun", "definition": "a commissioned officer in the army, navy, air force, or marine corps"},
    {"no": "384", "word": "cavalier", "part": "adjective", "definition": "given to airy dismissal of things worthy of attention"},
    {"no": "385", "word": "circumspectly", "part": "adverb", "definition": "in a manner marked by caution and earnest attention to all significant circumstances and possible consequences of action"},
    {"no": "386", "word": "chernobyl", "part": "geographical entry", "definition": "site in northern Ukraine of a town abandoned after a nuclear accident nearby in 1986"},
    {"no": "387", "word": "algebraic", "part": "adjective", "definition": "of, relating to, involving, or according to the laws of a branch of mathematics in which arithmetic relations are generalized and explored by using letter symbols to represent numbers, variable quantities, or other mathematical entities"},
    {"no": "388", "word": "hydraulics", "part": "plural noun", "definition": "a branch of science that deals with practical applications (as the transmission of energy or the effects of flow) of water or other liquid in motion"},
    {"no": "389", "word": "klystron", "part": "noun", "definition": "an electron tube in which bunching of electrons is produced by subjecting them to acceleration and deceleration by high potential across a gap and which is used for the generation and amplification of ultrahigh-frequency current (as in radar)"},
    {"no": "390", "word": "fuselage", "part": "noun", "definition": "the central body portion of an airplane designed to accommodate the crew and the passengers or cargo"},
    {"no": "391", "word": "grosgrain", "part": "noun", "definition": "a firm fabric in plain weave usually with a silk or rayon warp and a heavy cotton filling that forms pronounced crosswise ribs"},
    {"no": "392", "word": "byzantine", "part": "adjective", "definition": "having the characteristics of an architecture developed in the eastern Roman Empire having as its chief decorative feature the incrustation of walls with marble veneering and with richly colored mosaic on grounds of gold"},
    {"no": "393", "word": "objet dart", "part": "noun", "definition": "an article of artistic worth"},
    {"no": "394", "word": "seance", "part": "noun", "definition": "a meeting for the purpose of receiving spirit communications"},
    {"no": "395", "word": "reticule", "part": "noun", "definition": "a woman’s small drawstring bag used as a pocketbook, workbag, or carryall"},
    {"no": "396", "word": "defibrillator", "part": "noun", "definition": "a device that restores the heart’s normal rhythm"},
    {"no": "397", "word": "rookery", "part": "noun", "definition": "a breeding ground or common haunt of gregarious birds or animals (as herons, penguins, or seals); also : a colony of such birds or animals"},
    {"no": "398", "word": "vociferous", "part": "adjective", "definition": "marked by or given to ready vehement insistent outcry"},
    {"no": "399", "word": "carmelite", "part": "noun", "definition": "a member of a Roman Catholic mendicant order founded in the 12th century"},
    {"no": "400", "word": "cascabel", "part": "noun", "definition": "a vicious South and Central American rattlesnake that has a powerful neurotoxic venom and is the only rattlesnake of eastern South America"},
    {"no": "401", "word": "san joaquin", "part": "geographical entry", "definition": "a river in central California flowing from the Sierra Nevada southwest and then northwest into the Sacramento River"},
    {"no": "402", "word": "cabeza", "part": "noun", "definition": "the head of a person or animal"},
    {"no": "403", "word": "imperator", "part": "noun", "definition": "supreme leader especially of the ancient Romans : commander, emperor"},
    {"no": "404", "word": "physician", "part": "noun", "definition": "one duly authorized to treat disease : a doctor of medicine"},
    {"no": "405", "word": "symbolizes", "part": "verb", "definition": "serves as something that stands for or suggests something else by reason of relationship, association, convention, or accidental but not intentional resemblance"},
    {"no": "406", "word": "camouflaged", "part": "verb", "definition": "concealed by means of disguise"},
    {"no": "407", "word": "piñon", "part": "noun", "definition": "the nutlike seed of a low-growing nut pine of western North America used especially in confectionery"},
    {"no": "408", "word": "dysfunctional", "part": "adjective", "definition": "related to a trait or condition failing to serve a useful or adjustive purpose in society"},
    {"no": "409", "word": "creosote", "part": "noun", "definition": "a dark brown or black flammable tar deposited from especially wood smoke on the walls of a chimney"},
    {"no": "410", "word": "gravelly", "part": "adjective", "definition": "harsh and usually irritating or unpleasant — used especially of the human voice"},
    {"no": "411", "word": "keening", "part": "adjective", "definition": "having the quality of or suggesting a lamentation or cry of grief"},
    {"no": "412", "word": "probation", "part": "noun", "definition": "the action of suspending the sentence of a convicted offender in such a way that the offender is given freedom after promising good behavior and agreeing to a varying degree of supervision"},
    {"no": "413", "word": "aesthetic", "part": "adjective", "definition": "relating to the beautiful as distinguished from the merely pleasing, the moral, and especially the useful and utilitarian"},
    {"no": "414", "word": "suffocate", "part": "verb", "definition": "to die from being unable to breathe"},
    {"no": "415", "word": "endowed", "part": "verb", "definition": "furnished (as an institution) with an income"},
    {"no": "416", "word": "violence", "part": "noun", "definition": "intense, turbulent, or furious action, force, or feeling often destructive"},
    {"no": "417", "word": "immunization", "part": "noun", "definition": "the creation of a condition of being able to resist a particular disease"},
    {"no": "418", "word": "assizes", "part": "plural noun", "definition": "former periodical sessions of the judges of the superior courts in every county of England for the purpose of administering justice in the trial and determination of civil and criminal cases"},
    {"no": "419", "word": "stockade", "part": "noun", "definition": "a line of stout posts or timbers set firmly in the earth in contact with each other, usually furnished with loopholes, and designed to form a barrier or defensive fortification"},
    {"no": "420", "word": "gallipot", "part": "noun", "definition": "a small usually ceramic vessel with a small mouth; especially : one used by apothecaries to hold medicines"},
    {"no": "421", "word": "olympics", "part": "plural noun", "definition": "a modified revival of a Panhellenic festival originating in Athens in 1896, held once every four years, and consisting of international athletic contests"},
    {"no": "422", "word": "miscreant", "part": "noun", "definition": "one who behaves criminally or viciously"},
    {"no": "423", "word": "aquitaine", "part": "geographical entry", "definition": "historical region of southwestern France whose capital was Toulouse"},
    {"no": "424", "word": "muttonchops", "part": "plural noun", "definition": "side-whiskers that are narrow at the temple and broad and round by the lower jaws"},
    {"no": "425", "word": "charade", "part": "noun", "definition": "an almost transparent pretense"},
    {"no": "426", "word": "relegated", "part": "verb", "definition": "degraded : demoted"},
    {"no": "427", "word": "conspiratorial", "part": "adjective", "definition": "suggestive of an agreement manifesting itself in words or deeds and made by two or more persons confederating to do an unlawful act"},
    {"no": "428", "word": "puppeteer", "part": "noun", "definition": "one who manipulates small-scale figures of humans or other living beings"},
    {"no": "429", "word": "gullet", "part": "noun", "definition": "the tube by which food passes from the pharynx to the stomach : the esophagus"},
    {"no": "430", "word": "rancid", "part": "adjective", "definition": "having an offensive smell or taste usually from chemical change or decomposition"},
    {"no": "431", "word": "consensus", "part": "noun", "definition": "collective opinion : the judgment arrived at by most of those concerned"},
    {"no": "432", "word": "accommodations", "part": "plural noun", "definition": "lodgings, food, and services (as at a hotel)"},
    {"no": "433", "word": "emblem", "part": "noun", "definition": "a device, symbol, design, or figure adopted and used as an identifying mark"},
    {"no": "434", "word": "recoil", "part": "verb", "definition": "to shrink back especially with a sudden movement (as in horror, fear, disgust) : to move suddenly backward or away"},
    {"no": "435", "word": "upholstery", "part": "noun", "definition": "the materials (as fabric, padding, and springs) used to make a soft covering especially for a seat; specifically : the fabric used to cover a seat"},
    {"no": "436", "word": "effectual", "part": "adjective", "definition": "characterized by adequate power to produce an intended result"},
    {"no": "437", "word": "acquaintance", "part": "noun", "definition": "a not particularly close or intimate friend : a person with whom one has had some social contact but for whom one has no strong personal attachment"},
    {"no": "438", "word": "fandango", "part": "noun", "definition": "a lively Spanish dance usually performed by a man and woman with castanets and in triple time"},
    {"no": "439", "word": "puncheon", "part": "noun", "definition": "a large cask of varying capacity"},
    {"no": "440", "word": "operant", "part": "adjective", "definition": "relating to conditioning in which the desired behavior or increasingly closer approximations to it are followed by a rewarding or reinforcing stimulus — used in psychology"},
    {"no": "441", "word": "infrastructure", "part": "noun", "definition": "the system of public works of a country, state, or region"},
    {"no": "442", "word": "alighted", "part": "verb", "definition": "descended from or as if from the air and come to rest : landed, settled"},
    {"no": "443", "word": "canterbury", "part": "adjective", "definition": "of or from the city of the same name in England"},
    {"no": "444", "word": "barista", "part": "noun", "definition": "a person whose job is to prepare and serve coffee and similar drinks (such as espresso)"},
    {"no": "445", "word": "Choctaws", "part": "plural noun", "definition": "members of a Muskogean people of Mississippi, Alabama, and Louisiana"},
    {"no": "446", "word": "prosecutor", "part": "noun", "definition": "an attorney who conducts proceedings especially of a criminal nature in a court on behalf of the government"},
    {"no": "447", "word": "noncommittal", "part": "adjective", "definition": "taking no clear position or giving no clear indication of attitude, feeling, or point of view"},
    {"no": "448", "word": "eulogy", "part": "noun", "definition": "a composition (as a set oration) in commendation of someone or something (as of the character and services of a deceased person)"},
    {"no": "449", "word": "regales", "part": "verb", "definition": "gives pleasure or amusement to : affects pleasurably"},
    {"no": "450", "word": "psychometry", "part": "noun", "definition": "divination of facts concerning an object or its owner through contact with or proximity to the object"},
];
