const words = [
    {"no": "1", "word": "deep", "part": "adjective", "definition": "extending downward to a considerable degree"},
    {"no": "2", "word": "happy", "part": "adjective", "definition": "having the feeling arising from the consciousness of well-being"},
    {"no": "3", "word": "bump", "part": "verb", "definition": "to hit or knock typically with a degree of force or violence and making a thudding impact and usually with a degree of injury or damage"},
    {"no": "4", "word": "bear", "part": "noun", "definition": "an animal having long shaggy hair, feeding on fruit and insects as well as on flesh, and moving very fast for short distances"},
    {"no": "5", "word": "count", "part": "verb", "definition": "to separate one by one to find the total number of units : to number or tally"},
    {"no": "6", "word": "dunk", "part": "verb", "definition": "to dip (as a piece of bread, cake, or doughnut) into liquid (as coffee, milk, or tea) while eating"},
    {"no": "7", "word": "feet", "part": "plural noun", "definition": "the terminal parts of the vertebrate legs upon which an individual stands"},
    {"no": "8", "word": "cold", "part": "adjective", "definition": "having a temperature notably below that compatible with human comfort"},
    {"no": "9", "word": "alone", "part": "adjective", "definition": "away from other people or things"},
    {"no": "10", "word": "click", "part": "verb", "definition": "to select (something on a computer) by placing the cursor over it and pressing a button on your mouse"},
    {"no": "11", "word": "miss", "part": "verb", "definition": "to feel the lack of : to be unhappy because of the loss or absence of"},
    {"no": "12", "word": "shirt", "part": "noun", "definition": "a loose cloth garment usually having a collar, sleeves, a front opening, and a tail long enough to be tucked inside the waistband of trousers or a skirt"},
    {"no": "13", "word": "roof", "part": "noun", "definition": "the outside cover on top of a building or home"},
    {"no": "14", "word": "here", "part": "adverb", "definition": "at this point in space : in this location"},
    {"no": "15", "word": "lamp", "part": "noun", "definition": "a light-giving device"},
    {"no": "16", "word": "lost", "part": "adjective", "definition": "gone out of one's possession or control : put in an unremembered place"},
    {"no": "17", "word": "lunch", "part": "noun", "definition": "the meal that is eaten in the middle of the day"},
    {"no": "18", "word": "drift", "part": "verb", "definition": "to become driven or carried along by a current of water, wind, or air"},
    {"no": "19", "word": "please", "part": "adverb", "definition": "-used as a function word to express politeness or emphasis in a request"},
    {"no": "20", "word": "spill", "part": "verb", "definition": "to cause or allow to pour, splash, or fall out (as over the edge of a container) and be wasted, lost, or scattered"},
    {"no": "21", "word": "tired", "part": "adjective", "definition": "drained of strength and energy : fatigued often to the point of exhaustion : weary"},
    {"no": "22", "word": "large", "part": "adjective", "definition": "big"},
    {"no": "23", "word": "lake", "part": "noun", "definition": "a large body of water surrounded by land"},
    {"no": "24", "word": "grab", "part": "verb", "definition": "to take or take hold of by a sudden motion or grasp : to seize, to clutch"},
    {"no": "25", "word": "juice", "part": "noun", "definition": "the extractable fluid contents of plant cells or plant structures"},
    {"no": "26", "word": "nook", "part": "noun", "definition": "a secluded or out-of-the-way place or part"},
    {"no": "27", "word": "shops", "part": "verb", "definition": "examines goods and services with intent to buy"},
    {"no": "28", "word": "spot", "part": "noun", "definition": "a small extent of space"},
    {"no": "29", "word": "world", "part": "noun", "definition": "the earth with all its inhabitants and all things upon it"},
    {"no": "30", "word": "math", "part": "noun", "definition": "a science that deals with the relationship and symbolism of numbers"},
    {"no": "31", "word": "pick", "part": "verb", "definition": "to select from among a group"},
    {"no": "32", "word": "soap", "part": "noun", "definition": "a cleansing agent that is used for washing something"},
    {"no": "33", "word": "tools", "part": "plural noun", "definition": "instruments (such as hammers or saws) used or worked by hand"},
    {"no": "34", "word": "green", "part": "adjective", "definition": "being the color of grass or emeralds"},
    {"no": "35", "word": "muddy", "part": "adjective", "definition": "covered with a slimy sticky mixture of finely divided particles of solid material and water"},
    {"no": "36", "word": "ripe", "part": "adjective", "definition": "fully developed and so usable as food - used of fruit"},
    {"no": "37", "word": "sign", "part": "noun", "definition": "a board on a building that tells the name and type of a business"},
    {"no": "38", "word": "soup", "part": "noun", "definition": "a liquid food made with broth that often contains pieces of meat, fish, pasta, or vegetables"},
    {"no": "39", "word": "warm", "part": "adjective", "definition": "sending or giving out heat usually to a comfortable or beneficial degree : producing sensations of heat"},
    {"no": "40", "word": "fresh", "part": "adjective", "definition": "newly produced, gathered, or made"},
    {"no": "41", "word": "learn", "part": "verb", "definition": "to gain knowledge or understanding of or skill in by study, instruction, or experience"},
    {"no": "42", "word": "frosty", "part": "adjective", "definition": "cold, freezing"},
    {"no": "43", "word": "crisp", "part": "adjective", "definition": "easily broken, cracked, or snapped"},
    {"no": "44", "word": "shape", "part": "noun", "definition": "the visible makeup characteristic of a particular item or kind of item : characteristic appearance or visible form"},
    {"no": "45", "word": "splash", "part": "verb", "definition": "to strike and dash about (as water or mud) : to cause (a liquid or thinly viscous substance) to spatter or toss about especially with force"},
    {"no": "46", "word": "mushy", "part": "adjective", "definition": "soft, spongy"},
    {"no": "47", "word": "group", "part": "noun", "definition": "a relatively small number of individuals assembled or standing together"},
    {"no": "48", "word": "spine", "part": "noun", "definition": "the backbone of a book"},
    {"no": "49", "word": "straps", "part": "verb", "definition": "secures with or attaches by means of a narrow usually flat strip or thong of a flexible material"},
    {"no": "50", "word": "feast", "part": "noun", "definition": "an elaborate meal : a banquet"},
    {"no": "51", "word": "eagle", "part": "noun", "definition": "any of various large diurnal birds of prey noted for their strength, size, graceful figure, keenness of vision, and powers of flight"},
    {"no": "52", "word": "berries", "part": "plural noun", "definition": "pulpy and usually edible fruits of small size"},
    {"no": "53", "word": "caves", "part": "plural noun", "definition": "hollowed-out chambers in the earth or in the sides of cliffs or hills"},
    {"no": "54", "word": "blanket", "part": "noun", "definition": "a piece of warm fabric used as a bed covering"},
    {"no": "55", "word": "catch", "part": "verb", "definition": "to take hold of especially suddenly or forcibly : to grasp"},
    {"no": "56", "word": "updo", "part": "noun", "definition": "an upswept hairdo"},
    {"no": "57", "word": "mule", "part": "noun", "definition": "a hybrid between the horse and the donkey"},
    {"no": "58", "word": "glow", "part": "verb", "definition": "to shine with light or become lit up"},
    {"no": "59", "word": "quick", "part": "adjective", "definition": "done or taking place with rapidity : done or taking place within only a small interval of time"},
    {"no": "60", "word": "cotton", "part": "noun", "definition": "a soft fibrous usually white substance that clothes the seeds of various plants and is used extensively in the making of threads, yarns, and fabrics"},
    {"no": "61", "word": "seats", "part": "plural noun", "definition": "assigned or regularly assumed sitting places"},
    {"no": "62", "word": "baseball", "part": "noun", "definition": "a game played by two teams of nine in which players try to score runs by hitting a small ball with a bat and running to each of four bases located on a large field"},
    {"no": "63", "word": "great", "part": "adjective", "definition": "wonderful, admirable"},
    {"no": "64", "word": "playground", "part": "noun", "definition": "a piece of land used for and usually having special facilities for recreation especially by children"},
    {"no": "65", "word": "monster", "part": "noun", "definition": "a ferocious legendary animal usually of great size"},
    {"no": "66", "word": "enjoy", "part": "verb", "definition": "to make happy"},
    {"no": "67", "word": "jazzy", "part": "adjective", "definition": "of an unrestrained, animated, or flashy character"},
    {"no": "68", "word": "jeans", "part": "plural noun", "definition": "pants usually made of a durable twilled cotton cloth or denim and worn for work or sports"},
    {"no": "69", "word": "partner", "part": "noun", "definition": "one that is associated in any action with another : associate, colleague"},
    {"no": "70", "word": "raindrop", "part": "noun", "definition": "a liquid globule of water falling especially from the clouds"},
    {"no": "71", "word": "office", "part": "noun", "definition": "a place where a particular kind of business is transacted or a service is supplied"},
    {"no": "72", "word": "young", "part": "adjective", "definition": "in an early stage of life, growth, or development"},
    {"no": "73", "word": "outside", "part": "adverb", "definition": "in the open air"},
    {"no": "74", "word": "poem", "part": "noun", "definition": "writing in verse"},
    {"no": "75", "word": "pillow", "part": "noun", "definition": "a sack made typically of cloth and filled with a soft material used to support the head of a person resting or sleeping"},
    {"no": "76", "word": "steady", "part": "adjective", "definition": "firm in standing or position : not tottering or shaking : fixed"},
    {"no": "77", "word": "saturday", "part": "noun", "definition": "the seventh day of the week : the day following Friday"},
    {"no": "78", "word": "needle", "part": "noun", "definition": "a small slender rodlike instrument for hand sewing that has a round or elongated eye for thread at one end and a blunt or sharp point at the other and that is made usually of steel or bone in straight or curved form"},
    {"no": "79", "word": "above", "part": "adverb", "definition": "in a higher place : overhead"},
    {"no": "80", "word": "honking", "part": "verb", "definition": "causing (as a horn) to make a noise resembling the cry of a goose"},
    {"no": "81", "word": "strange", "part": "adjective", "definition": "unusual"},
    {"no": "82", "word": "noisy", "part": "adjective", "definition": "full of or characterized by the presence of sound"},
    {"no": "83", "word": "video", "part": "noun", "definition": "a recording of visual images and sound stored in digital form"},
    {"no": "84", "word": "timer", "part": "noun", "definition": "a stopwatch for timing races or contests"},
    {"no": "85", "word": "topics", "part": "plural noun", "definition": "subjects under discussion or consideration"},
    {"no": "86", "word": "layer", "part": "noun", "definition": "one thickness, course, or fold laid or lying over or under another"},
    {"no": "87", "word": "token", "part": "noun", "definition": "a piece or disk (as of metal) certified as having a definite value for payment or exchange"},
    {"no": "88", "word": "control", "part": "verb", "definition": "to have power over : to rule"},
    {"no": "89", "word": "summer", "part": "noun", "definition": "the season that consists of June, July, and August"},
    {"no": "90", "word": "across", "part": "preposition", "definition": "from one side to the opposite side of"},
    {"no": "91", "word": "stiff", "part": "adjective", "definition": "incapable of or resistant to being flexed or bent : rigid"},
    {"no": "92", "word": "running", "part": "verb", "definition": "going steadily by springing steps so that both feet leave the ground for an instant in each step"},
    {"no": "93", "word": "field", "part": "noun", "definition": "a land area free of woodland, cities, and towns : open country"},
    {"no": "94", "word": "behind", "part": "preposition", "definition": "toward the back : backward"},
    {"no": "95", "word": "trace", "part": "verb", "definition": "to copy (as a drawing, engraving, or manuscript) by following the lines or letters as seen through a transparent sheet superimposed on the original"},
    {"no": "96", "word": "below", "part": "preposition", "definition": "downward from"},
    {"no": "97", "word": "loose", "part": "adjective", "definition": "not rigidly fastened or securely attached : lacking a firm or tight connection : ready to move or come apart from an attachment"},
    {"no": "98", "word": "spare", "part": "adjective", "definition": "not being used : held for future or emergency use"},
    {"no": "99", "word": "cling", "part": "verb", "definition": "to adhere closely and firmly as if glued"},
    {"no": "100", "word": "grins", "part": "verb", "definition": "draws back the lips from the teeth in merriment or good humor"},
    {"no": "101", "word": "giraffe", "part": "noun", "definition": "a large fleet African ruminant mammal that is the tallest of living quadrupeds and has a very long rather stiff neck and a short coat of fawn or cream-colored hair marked with large reddish or brown blotches"},
    {"no": "102", "word": "groceries", "part": "plural noun", "definition": "articles of goods sold by a dealer in staple foodstuffs and usually meats and other foods"},
    {"no": "103", "word": "huddling", "part": "verb", "definition": "gathering in a group : pressing close together"},
    {"no": "104", "word": "jigsaw", "part": "noun", "definition": "a puzzle made by sawing or cutting a picture into small pieces to be fitted together"},
    {"no": "105", "word": "neighbors", "part": "plural noun", "definition": "ones that live next to or near others"},
    {"no": "106", "word": "gasped", "part": "verb", "definition": "caught the breath audibly often as an expression of shock, concern, or emotion"},
    {"no": "107", "word": "mansion", "part": "noun", "definition": "a home that is impressive due to its size"},
    {"no": "108", "word": "midday", "part": "noun", "definition": "noon"},
    {"no": "109", "word": "powwow", "part": "noun", "definition": "a North American Indian ceremony (as for the cure of disease, success in hunting, victory in war) often accompanied by great noise, feasting, and dancing"},
    {"no": "110", "word": "bazaar", "part": "noun", "definition": "a market place or market (as in the Middle East) that usually consists of rows of shops or stalls where all kinds of goods are offered for sale"},
    {"no": "111", "word": "astray", "part": "adverb", "definition": "into a wrong or mistaken way of thinking or acting"},
    {"no": "112", "word": "liquid", "part": "noun", "definition": "an extremely fluid substance that flows freely like water"},
    {"no": "113", "word": "fuel", "part": "noun", "definition": "a material (as coal, gas, oil, or wood) used to produce heat or power by burning"},
    {"no": "114", "word": "massive", "part": "adjective", "definition": "weighty : heavy"},
    {"no": "115", "word": "women", "part": "plural noun", "definition": "female human beings"},
    {"no": "116", "word": "chuckle", "part": "verb", "definition": "to laugh inwardly or quietly"},
    {"no": "117", "word": "handstand", "part": "noun", "definition": "an act of supporting the body on the hands with the trunk and legs balanced in air"},
    {"no": "118", "word": "machine", "part": "noun", "definition": "an assemblage of parts that are usually solid bodies that transmit forces, motion, and energy one to another in some predetermined manner and to some desired end (as for sewing a seam, hoisting a load, or maintaining an electric current)"},
    {"no": "119", "word": "leaking", "part": "verb", "definition": "letting a substance (as water or gas) or light in or out through a hole, crevice, or other opening"},
    {"no": "120", "word": "snazzy", "part": "adjective", "definition": "outstanding in style : conspicuously or flashily attractive"},
    {"no": "121", "word": "whee", "part": "interjection", "definition": "-used to express delight or general exuberance"},
    {"no": "122", "word": "welcome", "part": "noun", "definition": "a friendly greeting or reception given to a person when he or she arrives"},
    {"no": "123", "word": "pretend", "part": "verb", "definition": "to make believe"},
    {"no": "124", "word": "should", "part": "verb", "definition": "-used in auxiliary function to express what is probable or expected"},
    {"no": "125", "word": "sideways", "part": "adverb", "definition": "in a position so as to offer only the right or left lateral part of the body"},
    {"no": "126", "word": "muster", "part": "verb", "definition": "to bring together : to collect"},
    {"no": "127", "word": "include", "part": "verb", "definition": "to place, list, or rate as a part or component of a whole or of a larger group, class, or aggregate"},
    {"no": "128", "word": "sandwich", "part": "noun", "definition": "two or more slices of bread with a filling (as of meat, cheese, or vegetables) between them"},
    {"no": "129", "word": "Saturn", "part": "noun", "definition": "the sixth planet from the sun in our solar system, known for its prominent ring system"},
    {"no": "130", "word": "velvet", "part": "noun", "definition": "a clothing and upholstery fabric in a wide range of constructions and weights made of silk, rayon, cotton, nylon, or wool and characterized by a short soft dense pile"},
    {"no": "131", "word": "breathe", "part": "verb", "definition": "to draw air into and expel it out of the lungs : to inhale and exhale"},
    {"no": "132", "word": "taxicab", "part": "noun", "definition": "a chauffeur-driven automobile available on call to carry a passenger between any two points (as within a city) for a fare"},
    {"no": "133", "word": "report", "part": "noun", "definition": "a usually detailed account or statement"},
    {"no": "134", "word": "cobweb", "part": "noun", "definition": "a single thread spun by a spider"},
    {"no": "135", "word": "rodent", "part": "noun", "definition": "an animal of an order comprising relatively small gnawing mammals"},
    {"no": "136", "word": "spying", "part": "verb", "definition": "watching (as a person) in a furtive or stealthy manner for the purpose of secretly obtaining information for usually hostile purposes"},
    {"no": "137", "word": "showed", "part": "verb", "definition": "gave an explanation of : taught, informed, instructed"},
    {"no": "138", "word": "scribbly", "part": "adjective", "definition": "covered with or consisting of illegible or random marks written or drawn"},
    {"no": "139", "word": "recess", "part": "noun", "definition": "a time between classes during the school day that is used for rest or play"},
    {"no": "140", "word": "highway", "part": "noun", "definition": "a main direct road"},
    {"no": "141", "word": "reeds", "part": "plural noun", "definition": "tall grasses with slender often prominently jointed stems that grow especially in wet areas"},
    {"no": "142", "word": "bolts", "part": "plural noun", "definition": "wood or metal bars or rods used to fasten a door"},
    {"no": "143", "word": "squeeze", "part": "verb", "definition": "to exert pressure especially on opposite sides or parts of : to press together closely or tightly"},
    {"no": "144", "word": "softly", "part": "adverb", "definition": "in a manner that is pleasing or agreeable to the senses"},
    {"no": "145", "word": "wriggle", "part": "verb", "definition": "to move the body or a bodily part to and fro with short writhing motions like a worm : to squirm, writhe"},
    {"no": "146", "word": "motion", "part": "noun", "definition": "the action or process of a body passing from one place or position to another"},
    {"no": "147", "word": "terror", "part": "noun", "definition": "a state of intense fright or apprehension : stark fear"},
    {"no": "148", "word": "murky", "part": "adjective", "definition": "dark or dull in color"},
    {"no": "149", "word": "harvest", "part": "noun", "definition": "the amount of any natural product that is gathered"},
    {"no": "150", "word": "quill", "part": "noun", "definition": "a bird's feather; especially : one of the large stiff feathers of a bird's wing or tail"},
    {"no": "151", "word": "patio", "part": "noun", "definition": "a usually paved outdoor area that is next to a building and is used for dining and relaxing"},
    {"no": "152", "word": "braids", "part": "plural noun", "definition": "lengths of hair done up by interweaving three or more strands together"},
    {"no": "153", "word": "castle", "part": "noun", "definition": "a large fortified building often surrounded by a moat"},
    {"no": "154", "word": "costume", "part": "noun", "definition": "an outfit worn to create the appearance characteristic of a particular period, person, place, or thing"},
    {"no": "155", "word": "wagon", "part": "noun", "definition": "a heavy four-wheel usually uncovered vehicle designed especially for transporting bulky commodities and drawn originally by animals"},
    {"no": "156", "word": "wrench", "part": "verb", "definition": "twist violently to one side or out of line, shape, or position"},
    {"no": "157", "word": "indeed", "part": "adverb", "definition": "admittedly, undeniably"},
    {"no": "158", "word": "gerbils", "part": "plural noun", "definition": "burrowing desert rodents that have long hind legs well adapted for leaping"},
    {"no": "159", "word": "village", "part": "noun", "definition": "a small cluster of houses and other buildings (as stores and churches) forming a unit distinct from the surrounding countryside"},
    {"no": "160", "word": "critters", "part": "plural noun", "definition": "creatures, animals"},
    {"no": "161", "word": "stifle", "part": "verb", "definition": "to withhold from expression : to keep in check : to repress"},
    {"no": "162", "word": "dimple", "part": "noun", "definition": "a slight natural indentation or hollow in the surface of some part of the human body (as on a cheek or the chin)"},
    {"no": "163", "word": "brother", "part": "noun", "definition": "a male human being considered in his relation to another person having the same parents or having one parent in common"},
    {"no": "164", "word": "mistake", "part": "noun", "definition": "an unintentional error"},
    {"no": "165", "word": "harbor", "part": "noun", "definition": "a small bay or other sheltered part of a considerable body of water usually well protected against high waves and strong currents and deep enough to anchor ships or other craft"},
    {"no": "166", "word": "reunion", "part": "noun", "definition": "a meeting of persons long separated"},
    {"no": "167", "word": "balloon", "part": "noun", "definition": "a bag of silk or other tough light material shaped usually like a sphere, made nonporous, and filled with heated air or a gas lighter than air"},
    {"no": "168", "word": "nonsense", "part": "noun", "definition": "words or language having no meaning or conveying no intelligible ideas"},
    {"no": "169", "word": "bandits", "part": "plural noun", "definition": "outlaws who live by plunder, especially armed robbers"},
    {"no": "170", "word": "champion", "part": "noun", "definition": "a person who has surpassed all rivals in a competition or who fights for a cause"},
    {"no": "171", "word": "superb", "part": "adjective", "definition": "of the highest quality"},
    {"no": "172", "word": "tinge", "part": "verb", "definition": "to color with a slight shade or stain : to tint"},
    {"no": "173", "word": "outcome", "part": "noun", "definition": "something that follows from an activity or process : consequence, result"},
    {"no": "174", "word": "groves", "part": "plural noun", "definition": "smaller groups of trees than forests often without underwood and planted or growing naturally as if arranged by art"},
    {"no": "175", "word": "ghostly", "part": "adjective", "definition": "of or relating to a mark or visible sign left by something dead, lost, or no longer present"},
    {"no": "176", "word": "convince", "part": "verb", "definition": "to get someone to agree or believe by arguing a point"},
    {"no": "177", "word": "biology", "part": "noun", "definition": "the science of life"},
    {"no": "178", "word": "captive", "part": "adjective", "definition": "kept within bounds : confined"},
    {"no": "179", "word": "streamers", "part": "plural noun", "definition": "narrow free-floating strips (as of cloth or crepe paper)"},
    {"no": "180", "word": "speckled", "part": "adjective", "definition": "covered or marked with small marks or splotches : spotted"},
    {"no": "181", "word": "hopscotch", "part": "noun", "definition": "a child's game in which a player tosses a small object into the lined and numbered areas outlined on the ground, hops on one foot through the figure and back to the area in which the object lies, picks it up, and hops out trying to avoid errors"},
    {"no": "182", "word": "jumbled", "part": "adjective", "definition": "lacking order, coherence, sequence, or plan"},
    {"no": "183", "word": "naughty", "part": "adjective", "definition": "violating accepted standards of morality, good taste, or polite behavior"},
    {"no": "184", "word": "dodgy", "part": "adjective", "definition": "evasive, tricky"},
    {"no": "185", "word": "ballerina", "part": "noun", "definition": "a female dancer in a form of artistic dancing"},
    {"no": "186", "word": "cubism", "part": "noun", "definition": "the arbitrary arrangement and interrelation of contours and fragments of contours on a picture surface without necessary reference to natural objects or their structure"},
    {"no": "187", "word": "interact", "part": "verb", "definition": "to have an effect on one another"},
    {"no": "188", "word": "jerky", "part": "noun", "definition": "meat (as beef) that has been cut into long slices or strips and dried"},
    {"no": "189", "word": "diablo", "part": "noun", "definition": "an extremely and malignantly wicked person : a human fiend"},
    {"no": "190", "word": "ablaze", "part": "adjective", "definition": "on fire"},
    {"no": "191", "word": "pivot", "part": "noun", "definition": "a dance step in which the dancer rotates on one foot and completes the step by shifting the weight to the other foot"},
    {"no": "192", "word": "karate", "part": "noun", "definition": "a Japanese art of self-defense in which kicks and openhanded blows are delivered especially to vulnerable parts of the body"},
    {"no": "193", "word": "bowler", "part": "noun", "definition": "a stiff felt hat with a dome-shaped crown and a rather narrow somewhat rolled brim - called also 'Derby'"},
    {"no": "194", "word": "phantom", "part": "adjective", "definition": "unembodied, elusive"},
    {"no": "195", "word": "locust", "part": "noun", "definition": "a grasshopper that frequently travels in swarms"},
    {"no": "196", "word": "council", "part": "noun", "definition": "a somewhat permanent group elected or appointed to constitute an advisory body or a body with a degree of legislative power"},
    {"no": "197", "word": "ointment", "part": "noun", "definition": "a salve or unguent for application to the skin; specifically : a semisolid medicinal preparation usually having a base of fatty or greasy material"},
    {"no": "198", "word": "Gothic", "part": "adjective", "definition": "of, relating to or having the characteristics of a European style of architecture from the 12th to the 16th centuries that is characterized by slender vertical piers and counterbalancing buttresses, and with pointed arches and vaulting"},
    {"no": "199", "word": "midair", "part": "noun", "definition": "any point or region in the air not immediately adjacent to the ground or other solid or liquid surface beneath it"},
    {"no": "200", "word": "hurricane", "part": "noun", "definition": "a tropical cyclone with winds of 73 miles per hour or greater"},
    {"no": "201", "word": "laurel", "part": "noun", "definition": "a recognition of superior achievement : a mark of public esteem : an honor"},
    {"no": "202", "word": "lollygag", "part": "verb", "definition": "to fool around : to loiter, dawdle"},
    {"no": "203", "word": "vermin", "part": "plural noun", "definition": "small common harmful animals (such as bedbugs and mice) that tend to occur in great numbers and are difficult to control"},
    {"no": "204", "word": "argument", "part": "noun", "definition": "the act or process of contending or disagreeing in words : a disputation"},
    {"no": "205", "word": "wreckage", "part": "noun", "definition": "the remains of the destruction, disorganization, or serious injury of something especially by violence"},
    {"no": "206", "word": "dolphin", "part": "noun", "definition": "any of various small marine toothed whales that have the snout more or less elongated into a beak and the neck vertebrae partially fused"},
    {"no": "207", "word": "infinite", "part": "adjective", "definition": "having no end : extending indefinitely"},
    {"no": "208", "word": "bitter", "part": "adjective", "definition": "having a sharp, disagreeable taste : being one of the four basic taste sensations"},
    {"no": "209", "word": "catapults", "part": "plural noun", "definition": "ancient military devices used for hurling heavy missiles (as stones) or for hurling other missiles (as spears, arrows) with extreme force"},
    {"no": "210", "word": "embroiled", "part": "verb", "definition": "involved especially in conflict or with a problem, adversaries, or the law"},
    {"no": "211", "word": "burro", "part": "noun", "definition": "a donkey"},
    {"no": "212", "word": "guava", "part": "noun", "definition": "the globular yellow fruit of a small shrubby tropical American tree"},
    {"no": "213", "word": "crescendo", "part": "noun", "definition": "the peak of a gradual increase (as in physical or emotional force or intensity)"},
    {"no": "214", "word": "ocelot", "part": "noun", "definition": "a medium-sized American wildcat ranging from Texas to Patagonia and having a tawny yellow or grayish coat that is dotted and striped with black"},
    {"no": "215", "word": "onyx", "part": "adjective", "definition": "of the color jet black"},
    {"no": "216", "word": "demigod", "part": "noun", "definition": "a mythological divine or semidivine being (as the offspring of a deity and a mortal)"},
    {"no": "217", "word": "trek", "part": "noun", "definition": "a trip or movement especially when involving difficulties or complex organization"},
    {"no": "218", "word": "teriyaki", "part": "noun", "definition": "a dish of Japanese origin consisting of meat or fish that is grilled or broiled after being marinated in a seasoned soy sauce"},
    {"no": "219", "word": "contribute", "part": "verb", "definition": "to add (as knowledge or effort) to a common interest or activity"},
    {"no": "220", "word": "hocus-pocus", "part": "noun", "definition": "something that confuses, misleads, or is difficult to comprehend"},
    {"no": "221", "word": "narwhal", "part": "noun", "definition": "an arctic cetacean that has no dorsal fin, is marbled black and white in color, reaches a length of about 16 feet, and possesses in the male one or rarely two long, spirally twisted pointed tusks"},
    {"no": "222", "word": "melancholy", "part": "adjective", "definition": "depressed in spirits : mournful"},
    {"no": "223", "word": "merfolk", "part": "plural noun", "definition": "legendary peoples of the sea having human head, trunk, and arms and the tail of a fish"},
    {"no": "224", "word": "gargoyles", "part": "plural noun", "definition": "spouts often having the form of a grotesque figure or animal and projecting from a roof gutter to throw rainwater clear of a building"},
    {"no": "225", "word": "pavilions", "part": "plural noun", "definition": "light sometimes ornamental structures in gardens, parks, or places of recreation that are used for entertainment or shelter"},
    {"no": "226", "word": "skeptical", "part": "adjective", "definition": "characterized by an attitude of doubt or disposition in regard to something particular (such as a supposed fact)"},
    {"no": "227", "word": "palette", "part": "noun", "definition": "a particular range, quality, or use of color"},
    {"no": "228", "word": "ogres", "part": "plural noun", "definition": "hideous giants represented in fairy tales and folklore as feeding on human beings : monsters"},
    {"no": "229", "word": "goatee", "part": "noun", "definition": "a small trim pointed or tufted beard on a man's chin"},
    {"no": "230", "word": "grotesque", "part": "adjective", "definition": "departing markedly from the natural, the expected or the typical (as by distortion, exaggeration) : atypical"},
    {"no": "231", "word": "threshold", "part": "noun", "definition": "the place or point of entering or beginning : outset"},
    {"no": "232", "word": "flamboyant", "part": "adjective", "definition": "marked by strikingly elaborate, colorful, or showy display or behavior"},
    {"no": "233", "word": "famine", "part": "noun", "definition": "a period of extreme scarcity of food"},
    {"no": "234", "word": "linoleum", "part": "noun", "definition": "a floor covering made by laying on a burlap or canvas backing a mixture of solidified linseed oil and various solid particles and usually pigments"},
    {"no": "235", "word": "pesos", "part": "plural noun", "definition": "coins or currency notes representing any of the basic monetary units of Argentina, Chile, Colombia, Cuba, Dominican Republic, Mexico, and Uruguay"},
    {"no": "236", "word": "rogue", "part": "noun", "definition": "a dishonest unprincipled person"},
    {"no": "237", "word": "amnesia", "part": "noun", "definition": "loss of memory sometimes including the memory of personal identity"},
    {"no": "238", "word": "fruition", "part": "noun", "definition": "completion, fulfillment"},
    {"no": "239", "word": "bygone", "part": "adjective", "definition": "of or relating to the past"},
    {"no": "240", "word": "committee", "part": "noun", "definition": "a group of people delegated to consider, investigate, or act on and usually to report on some matter or business"},
    {"no": "241", "word": "mirage", "part": "noun", "definition": "an optical phenomenon observed on still days over deserts or hot pavements that has the mirrorlike appearance of a quiet pool of water"},
    {"no": "242", "word": "newfangled", "part": "adjective", "definition": "recently made or of the most up-to-date style"},
    {"no": "243", "word": "surcharge", "part": "noun", "definition": "a price demanded for a thing or service in excess of the usual or normal amount"},
    {"no": "244", "word": "marksmanship", "part": "noun", "definition": "the art or skill of a person practiced at hitting a target especially with firearms"},
    {"no": "245", "word": "column", "part": "noun", "definition": "one of a building's vertical supporting structures"},
    {"no": "246", "word": "plaque", "part": "noun", "definition": "an inscribed metal tablet that identifies a site or commemorates an individual or event"},
    {"no": "247", "word": "rebuke", "part": "verb", "definition": "to criticize sharply : to reprimand"},
    {"no": "248", "word": "adversity", "part": "noun", "definition": "a condition of suffering, destitution, or affliction often implying previous prosperity or well-being"},
    {"no": "249", "word": "symphony", "part": "noun", "definition": "a large piece for orchestra usually in three or four contrasting movements"},
    {"no": "250", "word": "aquamarine", "part": "noun", "definition": "a pale blue to light greenish blue"},
    {"no": "251", "word": "altar", "part": "noun", "definition": "a tablelike construction used in the Christian church in celebrating the Eucharist : communion table"},
    {"no": "252", "word": "stylistic", "part": "adjective", "definition": "of or relating to mode of expression especially in the use of language"},
    {"no": "253", "word": "flailed", "part": "verb", "definition": "moved, swung, or beat as though wielding an instrument for threshing grain from the ear by hand"},
    {"no": "254", "word": "errands", "part": "plural noun", "definition": "trips made in order to deliver a message or purchase or attend to something"},
    {"no": "255", "word": "spree", "part": "noun", "definition": "an unrestrained and usually excessive indulgence in or outburst of any activity : splurge, rampage"},
    {"no": "256", "word": "steeped", "part": "verb", "definition": "saturated thoroughly : imbued"},
    {"no": "257", "word": "smattering", "part": "noun", "definition": "an inconsiderable number or amount especially of similar but distinct individuals or parts : piecemeal collection"},
    {"no": "258", "word": "bibliophile", "part": "noun", "definition": "a lover of books especially for beautiful or rare qualities of format; also : a book collector"},
    {"no": "259", "word": "graphite", "part": "noun", "definition": "a mineral consisting of soft black lustrous carbon that conducts electricity and is used in pencils, crucibles, electrolytic anodes, as a lubricant, and as a moderator in atomic-energy plants - called also 'black lead'"},
    {"no": "260", "word": "halo", "part": "noun", "definition": "the aura of glory, veneration, prestige, or sentiment surrounding an idealized person or thing"},
    {"no": "261", "word": "feisty", "part": "adjective", "definition": "having or showing a lively aggressiveness : spunky"},
    {"no": "262", "word": "transfixed", "part": "verb", "definition": "held motionless by or as if by piercing especially with an absorbing emotion or interest"},
    {"no": "263", "word": "aluminum", "part": "noun", "definition": "a bluish silver-white metallic element that is the most plentiful metal in Earth's crust"},
    {"no": "264", "word": "residential", "part": "adjective", "definition": "used as a temporary or permanent dwelling place, abode, or habitation to which one intends to return"},
    {"no": "265", "word": "deposition", "part": "noun", "definition": "testimony taken down in writing under oath or affirmation"},
    {"no": "266", "word": "veterinarian", "part": "noun", "definition": "one qualified and duly authorized to treat diseases of animals"},
    {"no": "267", "word": "skiff", "part": "noun", "definition": "a light rowboat"},
    {"no": "268", "word": "totem", "part": "noun", "definition": "an animal, plant, or other object serving as the emblem of a family or clan and often regarded as a reminder of its ancestry"},
    {"no": "269", "word": "inferno", "part": "noun", "definition": "a large disastrous burning : a conflagration"},
    {"no": "270", "word": "buzzard", "part": "noun", "definition": "any of various birds of prey such as a turkey vulture or a condor"},
    {"no": "271", "word": "eliminate", "part": "verb", "definition": "to get rid of"},
    {"no": "272", "word": "writhes", "part": "verb", "definition": "becomes twisted, contorted, or wrested about in or as if in pain or struggling"},
    {"no": "273", "word": "mourners", "part": "plural noun", "definition": "those that are sorrowful over a death"},
    {"no": "274", "word": "respiratory", "part": "adjective", "definition": "of or relating to breathing"},
    {"no": "275", "word": "perpetrate", "part": "verb", "definition": "to be guilty of (a crime, an offense, etc.) : to commit"},
    {"no": "276", "word": "intestines", "part": "plural noun", "definition": "tubular portions of the digestive tract that in the vertebrate lie posterior to the stomach from which they are separated by the pyloric valve"},
    {"no": "277", "word": "sanitation", "part": "noun", "definition": "the application of measures to make environmental conditions favorable to health"},
    {"no": "278", "word": "barren", "part": "adjective", "definition": "deficient in producing vegetation : bare or desolate"},
    {"no": "279", "word": "lavishly", "part": "adverb", "definition": "in a manner characterized by profusion or excess"},
    {"no": "280", "word": "suffice", "part": "verb", "definition": "to be enough : to meet or satisfy a need"},
    {"no": "281", "word": "giddily", "part": "adverb", "definition": "in a manner characterized by exuberance, impulsiveness, or thoughtlessness"},
    {"no": "282", "word": "tiff", "part": "noun", "definition": "a slight fit of anger : an outburst of temper or spite : a petty quarrel"},
    {"no": "283", "word": "leeward", "part": "adjective", "definition": "situated away from the wind : downwind"},
    {"no": "284", "word": "hurly-burly", "part": "noun", "definition": "confusion, turmoil, uproar"},
    {"no": "285", "word": "monotone", "part": "noun", "definition": "a succession of syllables, words, or sentences in one unvaried key or pitch"},
    {"no": "286", "word": "parroting", "part": "verb", "definition": "imitating the form of without understanding the sense or meaning involved"},
    {"no": "287", "word": "techie", "part": "noun", "definition": "a person who is very knowledgeable or enthusiastic about the science of the application of knowledge to practical purposes"},
    {"no": "288", "word": "gruesome", "part": "adjective", "definition": "inspiring horror or repulsion : fearful, grisly, hideous"},
    {"no": "289", "word": "tsunami", "part": "noun", "definition": "a great sea wave produced by submarine earth movement or volcanic eruption : a tidal wave"},
    {"no": "290", "word": "anomaly", "part": "noun", "definition": "something deviating from a general rule, method, or analogy : something irregular or abnormal"},
    {"no": "291", "word": "banishment", "part": "noun", "definition": "legal expulsion from a country"},
    {"no": "292", "word": "magenta", "part": "noun", "definition": "a deep purplish red"},
    {"no": "293", "word": "conveyance", "part": "noun", "definition": "the action of transporting : transportation"},
    {"no": "294", "word": "cohort", "part": "noun", "definition": "company, band, group"},
    {"no": "295", "word": "kindling", "part": "noun", "definition": "easily combustible material of a convenient size for starting a fire"},
    {"no": "296", "word": "treachery", "part": "noun", "definition": "betrayal of trust"},
    {"no": "297", "word": "mañana", "part": "adverb", "definition": "at an indefinite time in the future - used chiefly in the Southwest"},
    {"no": "298", "word": "squeal", "part": "verb", "definition": "to cry with a sharp shrill prolonged sound"},
    {"no": "299", "word": "tersely", "part": "adverb", "definition": "in a brief and concise manner"},
    {"no": "300", "word": "autism", "part": "noun", "definition": "a developmental disorder that typically appears by age three and that is variable in expression but is recognized and diagnosed by impairment of the ability to form social relationships, by impairment of the ability to communicate with others, and by stereotyped behavior patterns"},
    {"no": "301", "word": "barracuda", "part": "noun", "definition": "any of several voracious predaceous marine fishes having an elongated body, projecting lower jaw, and strong teeth"},
    {"no": "302", "word": "boisterous", "part": "adjective", "definition": "noisily turbulent : rowdy"},
    {"no": "303", "word": "calamity", "part": "noun", "definition": "an event marked by great loss and lasting distress and affliction"},
    {"no": "304", "word": "formaldehyde", "part": "noun", "definition": "a colorless pungent gas used in water solution as a preservative and disinfectant"},
    {"no": "305", "word": "guru", "part": "noun", "definition": "a leader or teacher who is followed as a guide in spiritual or intellectual matters"},
    {"no": "306", "word": "hemlock", "part": "noun", "definition": "a tall biennial herb related to the carrot that has a mottled stem and poisonous juices"},
    {"no": "307", "word": "intricate", "part": "adjective", "definition": "worked out with great care in minute detail : complicated"},
    {"no": "308", "word": "kooky", "part": "adjective", "definition": "having the characteristics of an eccentric : crazy"},
    {"no": "309", "word": "lacerate", "part": "verb", "definition": "to tear or cut roughly or jaggedly : to wound"},
    {"no": "310", "word": "memento", "part": "noun", "definition": "something that serves to warn or remind : a souvenir"},
    {"no": "311", "word": "nirvana", "part": "noun", "definition": "a state of perfect happiness or peace"},
    {"no": "312", "word": "opulent", "part": "adjective", "definition": "exhibiting a luxurious richness or magnificence"},
    {"no": "313", "word": "pungent", "part": "adjective", "definition": "having a sharp or biting quality : acrid"},
    {"no": "314", "word": "reverie", "part": "noun", "definition": "the condition of being lost in thought : a daydream"},
    {"no": "315", "word": "savvy", "part": "noun", "definition": "practical understanding or know-how"},
    {"no": "316", "word": "tentacle", "part": "noun", "definition": "any of various elongate flexible usually tactile or prehensile processes borne by animals (such as insects, mollusks, worms) and usually on or about the head"},
    {"no": "317", "word": "vantage", "part": "noun", "definition": "a position giving a strategic advantage, commanding perspective, or comprehensive view"},
    {"no": "318", "word": "waddle", "part": "verb", "definition": "to walk with short steps swinging the forepart of the body from side to side"},
    {"no": "319", "word": "yearn", "part": "verb", "definition": "to feel a strong desire or longing"},
    {"no": "320", "word": "zany", "part": "adjective", "definition": "very eccentric or absurd often in an amusing way"},
    {"no": "321", "word": "annihilate", "part": "verb", "definition": "to destroy completely : to reduce to nothing"},
    {"no": "322", "word": "benevolent", "part": "adjective", "definition": "characterized by doing or disposed to do good : kindly"},
    {"no": "323", "word": "cantankerous", "part": "adjective", "definition": "marked by ill humor : difficult to deal with"},
    {"no": "324", "word": "debris", "part": "noun", "definition": "the remains of something broken down or destroyed"},
    {"no": "325", "word": "excavate", "part": "verb", "definition": "to dig out and remove : to hollow out"},
    {"no": "326", "word": "fiasco", "part": "noun", "definition": "a complete or ridiculous failure"},
    {"no": "327", "word": "gargantuan", "part": "adjective", "definition": "tremendous in size, volume, or degree : enormous"},
    {"no": "328", "word": "hapless", "part": "adjective", "definition": "having no luck : unfortunate"},
    {"no": "329", "word": "immaculate", "part": "adjective", "definition": "having no stain or blemish : spotlessly clean"},
    {"no": "330", "word": "juxtapose", "part": "verb", "definition": "to place side by side especially for comparison or contrast"},
    {"no": "331", "word": "kaleidoscope", "part": "noun", "definition": "an instrument containing loose bits of colored glass or plastic between two flat plates and two plane mirrors so placed that changes of position of the bits of material are reflected in an endless variety of symmetrical patterns"},
    {"no": "332", "word": "languid", "part": "adjective", "definition": "drooping or flagging from or as if from exhaustion : listless"},
    {"no": "333", "word": "mirth", "part": "noun", "definition": "gladness or gaiety as shown by or accompanied with laughter"},
    {"no": "334", "word": "nonchalant", "part": "adjective", "definition": "having an air of easy unconcern or indifference"},
    {"no": "335", "word": "obstreperous", "part": "adjective", "definition": "marked by unruly noisiness : aggressively boisterous"},
    {"no": "336", "word": "pinnacle", "part": "noun", "definition": "the highest point of development or achievement : summit"},
    {"no": "337", "word": "quixotic", "part": "adjective", "definition": "foolishly impractical especially in the pursuit of ideals"},
    {"no": "338", "word": "rendezvous", "part": "noun", "definition": "a meeting at an appointed place and time"},
    {"no": "339", "word": "serendipity", "part": "noun", "definition": "the phenomenon of finding valuable or delightful things when they are least expected"},
    {"no": "340", "word": "tantalize", "part": "verb", "definition": "to tease or torment by or as if by presenting something desirable to the view but continually keeping it out of reach"},
    {"no": "341", "word": "unscrupulous", "part": "adjective", "definition": "not controlled by a regard for what is right or fair : unprincipled"},
    {"no": "342", "word": "vexation", "part": "noun", "definition": "the quality or state of being annoyed : irritation"},
    {"no": "343", "word": "wistful", "part": "adjective", "definition": "full of yearning or desire tinged with melancholy"},
    {"no": "344", "word": "xenophobic", "part": "adjective", "definition": "characterized by fear and hatred of what is foreign or strange"},
    {"no": "345", "word": "yokel", "part": "noun", "definition": "a naive or gullible inhabitant of a rural area or small town"},
    {"no": "346", "word": "zealot", "part": "noun", "definition": "a person marked by fervent or fanatical devotion to a cause"},
    {"no": "347", "word": "ambidextrous", "part": "adjective", "definition": "able to use both hands with equal skill or ease"},
    {"no": "348", "word": "belligerent", "part": "adjective", "definition": "inclined to or exhibiting hostility or a combative nature"},
    {"no": "349", "word": "cacophony", "part": "noun", "definition": "harsh discordance of sound : dissonance"},
    {"no": "350", "word": "debilitate", "part": "verb", "definition": "to impair the strength of : to weaken"}
];
