const words = [
    {"no": "1", "word": "deep", "part": "adjective", "definition": "extending downward to a considerable degree"},
    {"no": "2", "word": "happy", "part": "adjective", "definition": "having the feeling arising from the consciousness of well-being"},
    {"no": "3", "word": "bump", "part": "verb", "definition": "to hit or knock typically with a degree of force or violence and making a thudding impact and usually with a degree of injury or damage"},
    {"no": "4", "word": "bear", "part": "noun", "definition": "an animal having long shaggy hair, feeding on fruit and insects as well as on flesh, and moving very fast for short distances"},
    {"no": "5", "word": "count", "part": "verb", "definition": "to separate one by one to find the total number of units : to number or tally"},
    {"no": "6", "word": "dunk", "part": "verb", "definition": "to dip (as a piece of bread, cake, or doughnut) into liquid (as coffee, milk, or tea) while eating"},
    {"no": "7", "word": "feet", "part": "plural noun", "definition": "the terminal parts of the vertebrate legs upon which an individual stands"},
    {"no": "8", "word": "cold", "part": "adjective", "definition": "having a temperature notably below that compatible with human comfort"},
    {"no": "9", "word": "alone", "part": "adjective", "definition": "away from other people or things"},
    {"no": "10", "word": "click", "part": "verb", "definition": "to select (something on a computer) by placing the cursor over it and pressing a button on your mouse"},
    {"no": "11", "word": "miss", "part": "verb", "definition": "to feel the lack of : to be unhappy because of the loss or absence of"},
    {"no": "12", "word": "shirt", "part": "noun", "definition": "a loose cloth garment usually having a collar, sleeves, a front opening, and a tail long enough to be tucked inside the waistband of trousers or a skirt"},
    {"no": "13", "word": "roof", "part": "noun", "definition": "the outside cover on top of a building or home"},
    {"no": "14", "word": "here", "part": "adverb", "definition": "at this point in space : in this location"},
    {"no": "15", "word": "lamp", "part": "noun", "definition": "a light-giving device"},
    {"no": "16", "word": "lost", "part": "adjective", "definition": "gone out of one's possession or control : put in an unremembered place"},
    {"no": "17", "word": "lunch", "part": "noun", "definition": "the meal that is eaten in the middle of the day"},
    {"no": "18", "word": "drift", "part": "verb", "definition": "to become driven or carried along by a current of water, wind, or air"},
    {"no": "19", "word": "please", "part": "adverb", "definition": "-used as a function word to express politeness or emphasis in a request"},
    {"no": "20", "word": "spill", "part": "verb", "definition": "to cause or allow to pour, splash, or fall out (as over the edge of a container) and be wasted, lost, or scattered"},
    {"no": "21", "word": "tired", "part": "adjective", "definition": "drained of strength and energy : fatigued often to the point of exhaustion : weary"},
    {"no": "22", "word": "large", "part": "adjective", "definition": "big"},
    {"no": "23", "word": "lake", "part": "noun", "definition": "a large body of water surrounded by land"},
    {"no": "24", "word": "grab", "part": "verb", "definition": "to take or take hold of by a sudden motion or grasp : to seize, to clutch"},
    {"no": "25", "word": "juice", "part": "noun", "definition": "the extractable fluid contents of plant cells or plant structures"},
    {"no": "26", "word": "nook", "part": "noun", "definition": "a secluded or out-of-the-way place or part"},
    {"no": "27", "word": "shops", "part": "verb", "definition": "examines goods and services with intent to buy"},
    {"no": "28", "word": "spot", "part": "noun", "definition": "a small extent of space"},
    {"no": "29", "word": "world", "part": "noun", "definition": "the earth with all its inhabitants and all things upon it"},
    {"no": "30", "word": "math", "part": "noun", "definition": "a science that deals with the relationship and symbolism of numbers"},
    {"no": "31", "word": "pick", "part": "verb", "definition": "to select from among a group"},
    {"no": "32", "word": "soap", "part": "noun", "definition": "a cleansing agent that is used for washing something"},
    {"no": "33", "word": "tools", "part": "plural noun", "definition": "instruments (such as hammers or saws) used or worked by hand"},
    {"no": "34", "word": "green", "part": "adjective", "definition": "being the color of grass or emeralds"},
    {"no": "35", "word": "muddy", "part": "adjective", "definition": "covered with a slimy sticky mixture of finely divided particles of solid material and water"},
    {"no": "36", "word": "ripe", "part": "adjective", "definition": "fully developed and so usable as food - used of fruit"},
    {"no": "37", "word": "sign", "part": "noun", "definition": "a board on a building that tells the name and type of a business"},
    {"no": "38", "word": "soup", "part": "noun", "definition": "a liquid food made with broth that often contains pieces of meat, fish, pasta, or vegetables"},
    {"no": "39", "word": "warm", "part": "adjective", "definition": "sending or giving out heat usually to a comfortable or beneficial degree : producing sensations of heat"},
    {"no": "40", "word": "fresh", "part": "adjective", "definition": "newly produced, gathered, or made"},
    {"no": "41", "word": "learn", "part": "verb", "definition": "to gain knowledge or understanding of or skill in by study, instruction, or experience"},
    {"no": "42", "word": "frosty", "part": "adjective", "definition": "cold, freezing"},
    {"no": "43", "word": "crisp", "part": "adjective", "definition": "easily broken, cracked, or snapped"},
    {"no": "44", "word": "shape", "part": "noun", "definition": "the visible makeup characteristic of a particular item or kind of item : characteristic appearance or visible form"},
    {"no": "45", "word": "splash", "part": "verb", "definition": "to strike and dash about (as water or mud) : to cause (a liquid or thinly viscous substance) to spatter or toss about especially with force"},
    {"no": "46", "word": "mushy", "part": "adjective", "definition": "soft, spongy"},
    {"no": "47", "word": "group", "part": "noun", "definition": "a relatively small number of individuals assembled or standing together"},
    {"no": "48", "word": "spine", "part": "noun", "definition": "the backbone of a book"},
    {"no": "49", "word": "straps", "part": "verb", "definition": "secures with or attaches by means of a narrow usually flat strip or thong of a flexible material"},
    {"no": "50", "word": "feast", "part": "noun", "definition": "an elaborate meal : a banquet"},
    {"no": "51", "word": "eagle", "part": "noun", "definition": "any of various large diurnal birds of prey noted for their strength, size, graceful figure, keenness of vision, and powers of flight"},
    {"no": "52", "word": "berries", "part": "plural noun", "definition": "pulpy and usually edible fruits of small size"},
    {"no": "53", "word": "caves", "part": "plural noun", "definition": "hollowed-out chambers in the earth or in the sides of cliffs or hills"},
    {"no": "54", "word": "blanket", "part": "noun", "definition": "a piece of warm fabric used as a bed covering"},
    {"no": "55", "word": "catch", "part": "verb", "definition": "to take hold of especially suddenly or forcibly : to grasp"},
    {"no": "56", "word": "updo", "part": "noun", "definition": "an upswept hairdo"},
    {"no": "57", "word": "mule", "part": "noun", "definition": "a hybrid between the horse and the donkey"},
    {"no": "58", "word": "glow", "part": "verb", "definition": "to shine with light or become lit up"},
    {"no": "59", "word": "quick", "part": "adjective", "definition": "done or taking place with rapidity : done or taking place within only a small interval of time"},
    {"no": "60", "word": "cotton", "part": "noun", "definition": "a soft fibrous usually white substance that clothes the seeds of various plants and is used extensively in the making of threads, yarns, and fabrics"},
    {"no": "61", "word": "seats", "part": "plural noun", "definition": "assigned or regularly assumed sitting places"},
    {"no": "62", "word": "baseball", "part": "noun", "definition": "a game played by two teams of nine in which players try to score runs by hitting a small ball with a bat and running to each of four bases located on a large field"},
    {"no": "63", "word": "great", "part": "adjective", "definition": "wonderful, admirable"},
    {"no": "64", "word": "playground", "part": "noun", "definition": "a piece of land used for and usually having special facilities for recreation especially by children"},
    {"no": "65", "word": "monster", "part": "noun", "definition": "a ferocious legendary animal usually of great size"},
    {"no": "66", "word": "enjoy", "part": "verb", "definition": "to make happy"},
    {"no": "67", "word": "jazzy", "part": "adjective", "definition": "of an unrestrained, animated, or flashy character"},
    {"no": "68", "word": "jeans", "part": "plural noun", "definition": "pants usually made of a durable twilled cotton cloth or denim and worn for work or sports"},
    {"no": "69", "word": "partner", "part": "noun", "definition": "one that is associated in any action with another : associate, colleague"},
    {"no": "70", "word": "raindrop", "part": "noun", "definition": "a liquid globule of water falling especially from the clouds"},
    {"no": "71", "word": "office", "part": "noun", "definition": "a place where a particular kind of business is transacted or a service is supplied"},
    {"no": "72", "word": "young", "part": "adjective", "definition": "in an early stage of life, growth, or development"},
    {"no": "73", "word": "outside", "part": "adverb", "definition": "in the open air"},
    {"no": "74", "word": "poem", "part": "noun", "definition": "writing in verse"},
    {"no": "75", "word": "pillow", "part": "noun", "definition": "a sack made typically of cloth and filled with a soft material used to support the head of a person resting or sleeping"},
    {"no": "76", "word": "steady", "part": "adjective", "definition": "firm in standing or position : not tottering or shaking : fixed"},
    {"no": "77", "word": "Saturday", "part": "noun", "definition": "the seventh day of the week : the day following Friday"},
    {"no": "78", "word": "needle", "part": "noun", "definition": "a small slender rodlike instrument for hand sewing that has a round or elongated eye for thread at one end and a blunt or sharp point at the other and that is made usually of steel or bone in straight or curved form"},
    {"no": "79", "word": "above", "part": "adverb", "definition": "in a higher place : overhead"},
    {"no": "80", "word": "honking", "part": "verb", "definition": "causing (as a horn) to make a noise resembling the cry of a goose"},
    {"no": "81", "word": "strange", "part": "adjective", "definition": "unusual"},
    {"no": "82", "word": "noisy", "part": "adjective", "definition": "full of or characterized by the presence of sound"},
    {"no": "83", "word": "video", "part": "noun", "definition": "a recording of visual images and sound stored in digital form"},
    {"no": "84", "word": "timer", "part": "noun", "definition": "a stopwatch for timing races or contests"},
    {"no": "85", "word": "topics", "part": "plural noun", "definition": "subjects under discussion or consideration"},
    {"no": "86", "word": "layer", "part": "noun", "definition": "one thickness, course, or fold laid or lying over or under another"},
    {"no": "87", "word": "token", "part": "noun", "definition": "a piece or disk (as of metal) certified as having a definite value for payment or exchange"},
    {"no": "88", "word": "control", "part": "verb", "definition": "to have power over : to rule"},
    {"no": "89", "word": "summer", "part": "noun", "definition": "the season that consists of June, July, and August"},
    {"no": "90", "word": "across", "part": "preposition", "definition": "from one side to the opposite side of"},
    {"no": "91", "word": "stiff", "part": "adjective", "definition": "incapable of or resistant to being flexed or bent : rigid"},
    {"no": "92", "word": "running", "part": "verb", "definition": "going steadily by springing steps so that both feet leave the ground for an instant in each step"},
    {"no": "93", "word": "field", "part": "noun", "definition": "a land area free of woodland, cities, and towns : open country"},
    {"no": "94", "word": "behind", "part": "preposition", "definition": "toward the back : backward"},
    {"no": "95", "word": "trace", "part": "verb", "definition": "to copy (as a drawing, engraving, or manuscript) by following the lines or letters as seen through a transparent sheet superimposed on the original"},
    {"no": "96", "word": "below", "part": "preposition", "definition": "downward from"},
    {"no": "97", "word": "loose", "part": "adjective", "definition": "not rigidly fastened or securely attached : lacking a firm or tight connection : ready to move or come apart from an attachment"},
    {"no": "98", "word": "spare", "part": "adjective", "definition": "not being used : held for future or emergency use"},
    {"no": "99", "word": "cling", "part": "verb", "definition": "to adhere closely and firmly as if glued"},
    {"no": "100", "word": "grins", "part": "verb", "definition": "draws back the lips from the teeth in merriment or good humor"},
    {"no": "101", "word": "giraffe", "part": "noun", "definition": "a large fleet African ruminant mammal that is the tallest of living quadrupeds and has a very long rather stiff neck and a short coat of fawn or cream-colored hair marked with large reddish or brown blotches"},
    {"no": "102", "word": "groceries", "part": "plural noun", "definition": "articles of goods sold by a dealer in staple foodstuffs and usually meats and other foods"},
    {"no": "103", "word": "huddling", "part": "verb", "definition": "gathering in a group : pressing close together"},
    {"no": "104", "word": "jigsaw", "part": "noun", "definition": "a puzzle made by sawing or cutting a picture into small pieces to be fitted together"},
    {"no": "105", "word": "neighbors", "part": "plural noun", "definition": "ones that live next to or near others"},
    {"no": "106", "word": "gasped", "part": "verb", "definition": "caught the breath audibly often as an expression of shock, concern, or emotion"},
    {"no": "107", "word": "mansion", "part": "noun", "definition": "a home that is impressive due to its size"},
    {"no": "108", "word": "midday", "part": "noun", "definition": "noon"},
    {"no": "109", "word": "powwow", "part": "noun", "definition": "a North American Indian ceremony (as for the cure of disease, success in hunting, victory in war) often accompanied by great noise, feasting, and dancing"},
    {"no": "110", "word": "bazaar", "part": "noun", "definition": "a market place or market (as in the Middle East) that usually consists of rows of shops or stalls where all kinds of goods are offered for sale"},
    {"no": "111", "word": "astray", "part": "adverb", "definition": "into a wrong or mistaken way of thinking or acting"},
    {"no": "112", "word": "liquid", "part": "noun", "definition": "an extremely fluid substance that flows freely like water"},
    {"no": "113", "word": "fuel", "part": "noun", "definition": "a material (as coal, gas, oil, or wood) used to produce heat or power by burning"},
    {"no": "114", "word": "massive", "part": "adjective", "definition": "weighty : heavy"},
    {"no": "115", "word": "women", "part": "plural noun", "definition": "female human beings"},
    {"no": "116", "word": "chuckle", "part": "verb", "definition": "to laugh inwardly or quietly"},
    {"no": "117", "word": "handstand", "part": "noun", "definition": "an act of supporting the body on the hands with the trunk and legs balanced in air"},
    {"no": "118", "word": "machine", "part": "noun", "definition": "an assemblage of parts that are usually solid bodies that transmit forces, motion, and energy one to another in some predetermined manner and to some desired end (as for sewing a seam, hoisting a load, or maintaining an electric current)"},
    {"no": "119", "word": "leaking", "part": "verb", "definition": "letting a substance (as water or gas) or light in or out through a hole, crevice, or other opening"},
    {"no": "120", "word": "snazzy", "part": "adjective", "definition": "outstanding in style : conspicuously or flashily attractive"},
    {"no": "121", "word": "whee", "part": "interjection", "definition": "-used to express delight or general exuberance"},
    {"no": "122", "word": "welcome", "part": "noun", "definition": "a friendly greeting or reception given to a person when he or she arrives"},
    {"no": "123", "word": "pretend", "part": "verb", "definition": "to make believe"},
    {"no": "124", "word": "should", "part": "verb", "definition": "-used in auxiliary function to express what is probable or expected"},
    {"no": "125", "word": "sideways", "part": "adverb", "definition": "in a position so as to offer only the right or left lateral part of the body"},
    {"no": "126", "word": "muster", "part": "verb", "definition": "to bring together : to collect"},
    {"no": "127", "word": "include", "part": "verb", "definition": "to place, list, or rate as a part or component of a whole or of a larger group, class, or aggregate"},
    {"no": "128", "word": "sandwich", "part": "noun", "definition": "two or more slices of bread with a filling (as of meat, cheese, or vegetables) between them"},
    {"no": "129", "word": "Saturn", "part": "noun", "definition": "the sixth planet from the sun in our solar system, known for its prominent ring system"},
    {"no": "130", "word": "velvet", "part": "noun", "definition": "a clothing and upholstery fabric in a wide range of constructions and weights made of silk, rayon, cotton, nylon, or wool and characterized by a short soft dense pile"},
    {"no": "131", "word": "breathe", "part": "verb", "definition": "to draw air into and expel it out of the lungs : to inhale and exhale"},
    {"no": "132", "word": "taxicab", "part": "noun", "definition": "a chauffeur-driven automobile available on call to carry a passenger between any two points (as within a city) for a fare"},
    {"no": "133", "word": "report", "part": "noun", "definition": "a usually detailed account or statement"},
    {"no": "134", "word": "cobweb", "part": "noun", "definition": "a single thread spun by a spider"},
    {"no": "135", "word": "rodent", "part": "noun", "definition": "an animal of an order comprising relatively small gnawing mammals"},
    {"no": "136", "word": "spying", "part": "verb", "definition": "watching (as a person) in a furtive or stealthy manner for the purpose of secretly obtaining information for usually hostile purposes"},
    {"no": "137", "word": "showed", "part": "verb", "definition": "gave an explanation of : taught, informed, instructed"},
    {"no": "138", "word": "scribbly", "part": "adjective", "definition": "covered with or consisting of illegible or random marks written or drawn"},
    {"no": "139", "word": "recess", "part": "noun", "definition": "a time between classes during the school day that is used for rest or play"},
    {"no": "140", "word": "highway", "part": "noun", "definition": "a main direct road"},
    {"no": "141", "word": "reeds", "part": "plural noun", "definition": "tall grasses with slender often prominently jointed stems that grow especially in wet areas"},
    {"no": "142", "word": "bolts", "part": "plural noun", "definition": "wood or metal bars or rods used to fasten a door"},
    {"no": "143", "word": "squeeze", "part": "verb", "definition": "to exert pressure especially on opposite sides or parts of : to press together closely or tightly"},
    {"no": "144", "word": "softly", "part": "adverb", "definition": "in a manner that is pleasing or agreeable to the senses"},
    {"no": "145", "word": "wriggle", "part": "verb", "definition": "to move the body or a bodily part to and fro with short writhing motions like a worm : to squirm, writhe"},
    {"no": "146", "word": "motion", "part": "noun", "definition": "the action or process of a body passing from one place or position to another"},
    {"no": "147", "word": "terror", "part": "noun", "definition": "a state of intense fright or apprehension : stark fear"},
    {"no": "148", "word": "murky", "part": "adjective", "definition": "dark or dull in color"},
    {"no": "149", "word": "harvest", "part": "noun", "definition": "the amount of any natural product that is gathered"},
    {"no": "150", "word": "quill", "part": "noun", "definition": "a bird's feather; especially : one of the large stiff feathers of a bird's wing or tail"},
    {"no": "151", "word": "patio", "part": "noun", "definition": "a usually paved outdoor area that is next to a building and is used for dining and relaxing"},
    {"no": "152", "word": "braids", "part": "plural noun", "definition": "lengths of hair done up by interweaving three or more strands together"},
    {"no": "153", "word": "castle", "part": "noun", "definition": "a large fortified building often surrounded by a moat"},
    {"no": "154", "word": "costume", "part": "noun", "definition": "an outfit worn to create the appearance characteristic of a particular period, person, place, or thing"},
    {"no": "155", "word": "wagon", "part": "noun", "definition": "a heavy four-wheel usually uncovered vehicle designed especially for transporting bulky commodities and drawn originally by animals"},
    {"no": "156", "word": "wrench", "part": "verb", "definition": "twist violently to one side or out of line, shape, or position"},
    {"no": "157", "word": "indeed", "part": "adverb", "definition": "admittedly, undeniably"},
    {"no": "158", "word": "gerbils", "part": "plural noun", "definition": "burrowing desert rodents that have long hind legs well adapted for leaping"},
    {"no": "159", "word": "village", "part": "noun", "definition": "a small cluster of houses and other buildings (as stores and churches) forming a unit distinct from the surrounding countryside"},
    {"no": "160", "word": "critters", "part": "plural noun", "definition": "creatures, animals"},
    {"no": "161", "word": "stifle", "part": "verb", "definition": "to withhold from expression : to keep in check : to repress"},
    {"no": "162", "word": "dimple", "part": "noun", "definition": "a slight natural indentation or hollow in the surface of some part of the human body (as on a cheek or the chin)"},
    {"no": "163", "word": "brother", "part": "noun", "definition": "a male human being considered in his relation to another person having the same parents or having one parent in common"},
    {"no": "164", "word": "mistake", "part": "noun", "definition": "an unintentional error"},
    {"no": "165", "word": "harbor", "part": "noun", "definition": "a small bay or other sheltered part of a considerable body of water usually well protected against high waves and strong currents and deep enough to anchor ships or other craft"},
    {"no": "166", "word": "reunion", "part": "noun", "definition": "a meeting of persons long separated"},
    {"no": "167", "word": "balloon", "part": "noun", "definition": "a bag of silk or other tough light material shaped usually like a sphere, made nonporous, and filled with heated air or a gas lighter than air"},
    {"no": "168", "word": "nonsense", "part": "noun", "definition": "words or language having no meaning or conveying no intelligible ideas"},
    {"no": "169", "word": "bandits", "part": "plural noun", "definition": "outlaws who live by plunder, especially armed robbers"},
    {"no": "170", "word": "champion", "part": "noun", "definition": "a person who has surpassed all rivals in a competition or who fights for a cause"},
    {"no": "171", "word": "superb", "part": "adjective", "definition": "of the highest quality"},
    {"no": "172", "word": "tinge", "part": "verb", "definition": "to color with a slight shade or stain : to tint"},
    {"no": "173", "word": "outcome", "part": "noun", "definition": "something that follows from an activity or process : consequence, result"},
    {"no": "174", "word": "groves", "part": "plural noun", "definition": "smaller groups of trees than forests often without underwood and planted or growing naturally as if arranged by art"},
    {"no": "175", "word": "ghostly", "part": "adjective", "definition": "of or relating to a mark or visible sign left by something dead, lost, or no longer present"},
    {"no": "176", "word": "convince", "part": "verb", "definition": "to get someone to agree or believe by arguing a point"},
    {"no": "177", "word": "biology", "part": "noun", "definition": "the science of life"},
    {"no": "178", "word": "captive", "part": "adjective", "definition": "kept within bounds : confined"},
    {"no": "179", "word": "streamers", "part": "plural noun", "definition": "narrow free-floating strips (as of cloth or crepe paper)"},
    {"no": "180", "word": "speckled", "part": "adjective", "definition": "covered or marked with small marks or splotches : spotted"},
    {"no": "181", "word": "hopscotch", "part": "noun", "definition": "a child's game in which a player tosses a small object into the lined and numbered areas outlined on the ground, hops on one foot through the figure and back to the area in which the object lies, picks it up, and hops out trying to avoid errors"},
    {"no": "182", "word": "jumbled", "part": "adjective", "definition": "lacking order, coherence, sequence, or plan"},
    {"no": "183", "word": "naughty", "part": "adjective", "definition": "violating accepted standards of morality, good taste, or polite behavior"},
    {"no": "184", "word": "dodgy", "part": "adjective", "definition": "evasive, tricky"},
    {"no": "185", "word": "ballerina", "part": "noun", "definition": "a female dancer in a form of artistic dancing"},
    {"no": "186", "word": "cubism", "part": "noun", "definition": "the arbitrary arrangement and interrelation of contours and fragments of contours on a picture surface without necessary reference to natural objects or their structure"},
    {"no": "187", "word": "interact", "part": "verb", "definition": "to have an effect on one another"},
    {"no": "188", "word": "jerky", "part": "noun", "definition": "meat (as beef) that has been cut into long slices or strips and dried"},
    {"no": "189", "word": "diablo", "part": "noun", "definition": "an extremely and malignantly wicked person : a human fiend"},
    {"no": "190", "word": "ablaze", "part": "adjective", "definition": "on fire"},
    {"no": "191", "word": "pivot", "part": "noun", "definition": "a dance step in which the dancer rotates on one foot and completes the step by shifting the weight to the other foot"},
    {"no": "192", "word": "karate", "part": "noun", "definition": "a Japanese art of self-defense in which kicks and openhanded blows are delivered especially to vulnerable parts of the body"},
    {"no": "193", "word": "bowler", "part": "noun", "definition": "a stiff felt hat with a dome-shaped crown and a rather narrow somewhat rolled brim - called also 'Derby'"},
    {"no": "194", "word": "phantom", "part": "adjective", "definition": "unembodied, elusive"},
    {"no": "195", "word": "locust", "part": "noun", "definition": "a grasshopper that frequently travels in swarms"},
    {"no": "196", "word": "council", "part": "noun", "definition": "a somewhat permanent group elected or appointed to constitute an advisory body or a body with a degree of legislative power"},
    {"no": "197", "word": "ointment", "part": "noun", "definition": "a salve or unguent for application to the skin; specifically : a semisolid medicinal preparation usually having a base of fatty or greasy material"},
    {"no": "198", "word": "Gothic", "part": "adjective", "definition": "of, relating to or having the characteristics of a European style of architecture from the 12th to the 16th centuries that is characterized by slender vertical piers and counterbalancing buttresses, and with pointed arches and vaulting"},
    {"no": "199", "word": "midair", "part": "noun", "definition": "any point or region in the air not immediately adjacent to the ground or other solid or liquid surface beneath it"},
    {"no": "200", "word": "hurricane", "part": "noun", "definition": "a tropical cyclone with winds of 73 miles per hour or greater"}
];
